import type { Client, Audit, AuditSection, AuditAsset, Annotation, IndustryExample, FlowPerformance, Recommendation, HealthScoreItem } from './types';

export const DEMO_CLIENTS: Client[] = [
  {
    id: 'demo-client-1',
    name: 'Bloom & Petal',
    company_name: 'Bloom & Petal Co.',
    website_url: 'https://bloomandpetal.com',
    industry: 'Horticulture / Plants',
    esp_platform: 'Klaviyo',
    api_key_placeholder: '',
    notes: 'Premium plant subscription service. Growing fast, email is their primary retention channel.',
    created_by: 'demo-user',
    created_at: '2025-02-15T10:00:00Z',
  },
  {
    id: 'demo-client-2',
    name: 'Luxe Glow Beauty',
    company_name: 'Luxe Glow Inc.',
    website_url: 'https://luxeglowbeauty.com',
    industry: 'Beauty / Cosmetics',
    esp_platform: 'Klaviyo',
    api_key_placeholder: '',
    notes: 'DTC skincare brand looking to improve lifecycle marketing. Currently heavy on campaigns, light on flows.',
    created_by: 'demo-user',
    created_at: '2025-01-20T14:30:00Z',
  },
  {
    id: 'demo-client-3',
    name: 'ThreadCraft Apparel',
    company_name: 'ThreadCraft LLC',
    website_url: 'https://threadcraft.co',
    industry: 'Clothing & Apparel',
    esp_platform: 'Klaviyo',
    api_key_placeholder: '',
    notes: 'Sustainable fashion brand. Strong brand identity but underutilizing email automation.',
    created_by: 'demo-user',
    created_at: '2025-03-01T09:15:00Z',
  },
];

export const DEMO_AUDITS: Audit[] = [
  {
    id: 'demo-audit-1',
    client_id: 'demo-client-2',
    title: 'Luxe Glow Beauty - Full Klaviyo Audit',
    status: 'published',
    audit_method: 'screenshot',
    list_size: 45000,
    aov: 68,
    monthly_traffic: 120000,
    total_revenue_opportunity: 12450,
    executive_summary: `Luxe Glow Beauty has built a solid foundation with Klaviyo, but significant revenue is being left on the table. Our analysis reveals that automated flows account for only 12% of total email revenue — well below the 35-45% benchmark for leading DTC beauty brands.\n\nThe most critical gaps are in flow architecture (missing browse abandonment, post-purchase, and winback flows), segmentation strategy (batch-and-blast approach to 85% of sends), and signup form optimization (current popup converting at 1.2% vs. 5-7% industry best practice).\n\nImplementing our recommended optimizations across these areas could unlock an estimated $12,450/month in additional email-attributed revenue within 90 days.`,
    created_by: 'demo-user',
    created_at: '2025-02-25T10:00:00Z',
    updated_at: '2025-03-10T16:30:00Z',
    published_at: '2025-03-10T16:30:00Z',
    public_share_token: 'demo-report-luxeglow',
    show_recommendations: true,
  },
  {
    id: 'demo-audit-2',
    client_id: 'demo-client-1',
    title: 'Bloom & Petal - Q1 Email Audit',
    status: 'in_progress',
    audit_method: 'api',
    list_size: 28000,
    aov: 52,
    monthly_traffic: 85000,
    total_revenue_opportunity: 7800,
    executive_summary: '',
    created_by: 'demo-user',
    created_at: '2025-03-05T09:00:00Z',
    updated_at: '2025-03-15T11:00:00Z',
    published_at: null,
    public_share_token: null,
    show_recommendations: false,
  },
  {
    id: 'demo-audit-3',
    client_id: 'demo-client-3',
    title: 'ThreadCraft - Lifecycle Marketing Assessment',
    status: 'completed',
    audit_method: 'screenshot',
    list_size: 62000,
    aov: 95,
    monthly_traffic: 200000,
    total_revenue_opportunity: 18200,
    executive_summary: `ThreadCraft has strong brand recognition and an engaged subscriber base, but their email program is heavily campaign-dependent. With 62,000 subscribers and high average order values, optimizing their automation stack represents a substantial revenue opportunity.`,
    created_by: 'demo-user',
    created_at: '2025-03-01T14:00:00Z',
    updated_at: '2025-03-12T10:00:00Z',
    published_at: null,
    public_share_token: 'demo-report-threadcraft',
    show_recommendations: false,
  },
];

export const DEMO_AUDIT_SECTIONS: AuditSection[] = [
  {
    id: 'demo-section-1',
    audit_id: 'demo-audit-1',
    section_key: 'account_health',
    current_state_title: 'Baseline Account Performance',
    optimized_state_title: 'Industry-Leading Benchmark',
    current_state_notes: 'Email revenue accounts for 18% of total revenue, below the 25-35% benchmark for DTC beauty brands. Deliverability sits at 94.2%, impacted by a large segment of unengaged subscribers. Campaign open rates average 16.8% — roughly 30% below top-performing beauty brands on Klaviyo.',
    optimized_notes: 'Top-tier beauty brands on Klaviyo generate 30-40% of total revenue from email. Deliverability above 98% is achievable through proper list hygiene. Open rates of 22-28% are standard with proper segmentation and send-time optimization.',
    ai_findings: 'Below-benchmark email revenue share, deliverability at risk, high unengaged subscriber ratio, flow revenue contribution critically low at 12%.',
    human_edited_findings: 'The account shows strong potential but is underperforming in three critical areas: flow revenue contribution (12% vs 35-45% benchmark), deliverability (94.2% vs 98%+ target), and engagement rates (16.8% open rate vs 22-28% benchmark).',
    summary_text: 'Luxe Glow has a solid subscriber base but is significantly underperforming relative to beauty industry benchmarks. The primary opportunities lie in shifting revenue from manual campaigns to automated flows and improving list health.',
    revenue_opportunity: 2100,
    confidence: 'high',
    status: 'approved',
  },
  {
    id: 'demo-section-2',
    audit_id: 'demo-audit-1',
    section_key: 'flows',
    current_state_title: 'Current Flow Architecture',
    optimized_state_title: 'Recommended Flow Strategy',
    current_state_notes: 'Only 3 active flows: Welcome Series (2 emails), Abandoned Cart (1 email), and a basic Post-Purchase thank you. No browse abandonment, winback, back-in-stock, or sunset flows. Welcome series lacks conditional splits and has no product recommendation logic. Abandoned cart flow triggers too late (4 hours) with generic copy.',
    optimized_notes: 'Implement a full 7-flow automation stack: multi-step Abandoned Cart (3-4 emails with dynamic product blocks), Browse Abandonment (2-3 emails), expanded Welcome Series (5-7 emails with preference collection), Post-Purchase with cross-sell logic, Winback at 60/90/120 day intervals, Back-in-Stock notifications, and Sunset flow for list hygiene.',
    ai_findings: 'Critical flow gaps: Missing browse abandonment ($3,600-$6,750/mo potential), underdeveloped welcome series, single-email cart abandonment, no winback automation, no sunset/list cleaning flow.',
    human_edited_findings: 'Flow architecture is the single biggest revenue opportunity. Adding browse abandonment and expanding the cart flow alone could generate $5,000-$8,000/month. The winback flow addresses the growing inactive segment that is hurting deliverability.',
    summary_text: 'The current flow setup covers only the basics and is missing 4 of the 7 core automated flows. This is the highest-impact area for improvement and represents the majority of the identified revenue opportunity.',
    revenue_opportunity: 5400,
    confidence: 'high',
    status: 'approved',
  },
  {
    id: 'demo-section-3',
    audit_id: 'demo-audit-1',
    section_key: 'segmentation',
    current_state_title: 'Current Segmentation Approach',
    optimized_state_title: 'Advanced Segmentation Framework',
    current_state_notes: 'Using 4 basic segments: All Subscribers, Recent Purchasers (90 days), VIP (3+ orders), and New Subscribers (30 days). 78% of campaign sends go to "All Subscribers." No engagement-based segmentation, no RFM model, no browse behavior segments.',
    optimized_notes: 'Build a 12-15 segment framework including: Engagement tiers (30/60/90/120 day activity), RFM scoring (High Value, Growth, At-Risk, Lapsed), Product Category interest, Purchase frequency, Browse behavior, and Lifecycle stage. Tailor campaign content and frequency to each segment.',
    ai_findings: 'Batch-and-blast approach to 78% of sends is depressing engagement metrics and likely triggering spam filters. No engagement tiers or behavioral segmentation detected.',
    human_edited_findings: 'The lack of segmentation is directly contributing to below-benchmark open rates and deliverability issues. Implementing engagement-based sending alone typically improves open rates by 15-25% within the first month.',
    summary_text: 'Moving from a batch-and-blast approach to a segmented strategy will improve all key email metrics — open rates, click rates, conversion, and deliverability — while reducing unsubscribes.',
    revenue_opportunity: 1800,
    confidence: 'medium',
    status: 'approved',
  },
  {
    id: 'demo-section-4',
    audit_id: 'demo-audit-1',
    section_key: 'campaigns',
    current_state_title: 'Current Campaign Strategy',
    optimized_state_title: 'Optimized Campaign Cadence',
    current_state_notes: 'Averaging 2.1 campaigns per week with inconsistent scheduling. Content is 90% promotional (discount-driven). No content calendar, no A/B testing program, no performance benchmarking against industry standards.',
    optimized_notes: 'Establish a consistent 3-4x/week cadence: 2 promotional, 1 educational/value-add, 1 engagement/community. Implement systematic A/B testing (subject lines, content blocks, send times). Create a rolling 4-week content calendar with seasonal planning.',
    ai_findings: 'Over-reliance on discount campaigns, inconsistent cadence, no testing framework, limited content variety. Discount fatigue likely contributing to declining engagement.',
    human_edited_findings: 'The campaign program needs both structural improvement (consistency, variety) and tactical optimization (testing, segmented sends). The current discount-heavy approach is training subscribers to wait for sales.',
    summary_text: 'A more structured and varied campaign approach will reduce discount dependency, improve engagement metrics, and create a more sustainable revenue model from email campaigns.',
    revenue_opportunity: 1200,
    confidence: 'medium',
    status: 'approved',
  },
  {
    id: 'demo-section-5',
    audit_id: 'demo-audit-1',
    section_key: 'email_design',
    current_state_title: 'Current Email Design Quality',
    optimized_state_title: 'Design Best Practices',
    current_state_notes: 'Templates are functional but dated. Heavy use of stock imagery rather than lifestyle/brand photography. CTAs are buried below the fold in most emails. Mobile experience is passable but not optimized — text runs small and buttons are hard to tap. No dynamic content blocks or personalization elements.',
    optimized_notes: 'Redesign templates with mobile-first approach, prominent CTA placement above the fold, brand-consistent imagery, dynamic product recommendation blocks, and personalized content sections. Use a modular template system for efficient campaign production.',
    ai_findings: 'Design gaps: CTAs below fold, poor mobile optimization, no dynamic content, inconsistent brand application, missing personalization elements.',
    human_edited_findings: 'Email design directly impacts click-through rates and conversions. The current templates are leaving revenue on the table through poor CTA placement and suboptimal mobile experience. A template refresh with mobile-first principles is needed.',
    summary_text: 'Modernizing email design to prioritize mobile experience, clear CTAs, and brand consistency will have an immediate positive impact on click-through and conversion rates.',
    revenue_opportunity: 750,
    confidence: 'medium',
    status: 'approved',
  },
  {
    id: 'demo-section-6',
    audit_id: 'demo-audit-1',
    section_key: 'signup_forms',
    current_state_title: 'Current Signup Form Setup',
    optimized_state_title: 'Optimized Form Strategy',
    current_state_notes: 'Single popup form offering 10% discount. Triggers immediately on page load with no targeting rules. Converting at 1.2% — well below the 4-6% benchmark for optimized beauty brand popups. No exit-intent form, no embedded forms, no multi-step flow.',
    optimized_notes: 'Deploy a multi-step popup with: 8-second delay trigger, exit-intent secondary trigger, scroll-depth trigger on collection pages. Add embedded forms in footer, blog posts, and product pages. Consider gamified elements (quiz, skin type match) to drive 5-7% conversion rates.',
    ai_findings: 'Popup converts at 1.2% vs 5-7% benchmark. Immediate trigger is causing high close rates. No exit-intent capture, no embedded forms, no multi-step flow.',
    human_edited_findings: 'The signup form gap represents fast, high-confidence revenue. Improving popup conversion from 1.2% to 5% would add approximately 4,560 new subscribers per month at current traffic levels. At average subscriber value of $2.50/month, this compounds significantly.',
    summary_text: 'Optimizing signup forms is the quickest win in this audit. Simple changes to trigger timing, form design, and the addition of exit-intent capture can 3-4x current conversion rates.',
    revenue_opportunity: 1200,
    confidence: 'high',
    status: 'approved',
  },
];

export const DEMO_ASSETS: AuditAsset[] = [
  {
    id: 'demo-asset-1',
    audit_id: 'demo-audit-1',
    client_id: 'demo-client-2',
    asset_type: 'screenshot',
    file_url: 'https://images.pexels.com/photos/3735218/pexels-photo-3735218.jpeg?auto=compress&cs=tinysrgb&w=800',
    file_name: 'current-email-design.jpg',
    section_key: 'email_design',
    side: 'current',
    uploaded_at: '2025-03-01T10:00:00Z',
  },
  {
    id: 'demo-asset-2',
    audit_id: 'demo-audit-1',
    client_id: 'demo-client-2',
    asset_type: 'screenshot',
    file_url: 'https://images.pexels.com/photos/3685530/pexels-photo-3685530.jpeg?auto=compress&cs=tinysrgb&w=800',
    file_name: 'optimized-email-benchmark.jpg',
    section_key: 'email_design',
    side: 'optimized',
    uploaded_at: '2025-03-01T10:00:00Z',
  },
  {
    id: 'demo-asset-3',
    audit_id: 'demo-audit-1',
    client_id: 'demo-client-2',
    asset_type: 'screenshot',
    file_url: 'https://images.pexels.com/photos/3760067/pexels-photo-3760067.jpeg?auto=compress&cs=tinysrgb&w=800',
    file_name: 'current-popup-form.jpg',
    section_key: 'signup_forms',
    side: 'current',
    uploaded_at: '2025-03-01T10:00:00Z',
  },
  {
    id: 'demo-asset-4',
    audit_id: 'demo-audit-1',
    client_id: 'demo-client-2',
    asset_type: 'screenshot',
    file_url: 'https://images.pexels.com/photos/3762879/pexels-photo-3762879.jpeg?auto=compress&cs=tinysrgb&w=800',
    file_name: 'optimized-popup-benchmark.jpg',
    section_key: 'signup_forms',
    side: 'optimized',
    uploaded_at: '2025-03-01T10:00:00Z',
  },
  {
    id: 'demo-asset-5',
    audit_id: 'demo-audit-1',
    client_id: 'demo-client-2',
    asset_type: 'screenshot',
    file_url: 'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg?auto=compress&cs=tinysrgb&w=800',
    file_name: 'current-flow-builder.jpg',
    section_key: 'flows',
    side: 'current',
    uploaded_at: '2025-03-01T10:00:00Z',
  },
  {
    id: 'demo-asset-6',
    audit_id: 'demo-audit-1',
    client_id: 'demo-client-2',
    asset_type: 'screenshot',
    file_url: 'https://images.pexels.com/photos/4050315/pexels-photo-4050315.jpeg?auto=compress&cs=tinysrgb&w=800',
    file_name: 'optimized-flow-benchmark.jpg',
    section_key: 'flows',
    side: 'optimized',
    uploaded_at: '2025-03-01T10:00:00Z',
  },
];

export const DEMO_ANNOTATIONS: Annotation[] = [
  {
    id: 'demo-ann-1',
    audit_section_id: 'demo-section-5',
    asset_id: 'demo-asset-1',
    x_position: 25,
    y_position: 35,
    label: 'CTA buried below fold',
    side: 'current',
    created_at: '2025-03-02T10:00:00Z',
  },
  {
    id: 'demo-ann-2',
    audit_section_id: 'demo-section-5',
    asset_id: 'demo-asset-1',
    x_position: 70,
    y_position: 15,
    label: 'Generic stock imagery',
    side: 'current',
    created_at: '2025-03-02T10:00:00Z',
  },
  {
    id: 'demo-ann-3',
    audit_section_id: 'demo-section-5',
    asset_id: 'demo-asset-2',
    x_position: 50,
    y_position: 20,
    label: 'Strong hero with brand photography',
    side: 'optimized',
    created_at: '2025-03-02T10:00:00Z',
  },
  {
    id: 'demo-ann-4',
    audit_section_id: 'demo-section-5',
    asset_id: 'demo-asset-2',
    x_position: 50,
    y_position: 55,
    label: 'CTA above fold, high contrast',
    side: 'optimized',
    created_at: '2025-03-02T10:00:00Z',
  },
  {
    id: 'demo-ann-5',
    audit_section_id: 'demo-section-6',
    asset_id: 'demo-asset-3',
    x_position: 50,
    y_position: 40,
    label: 'Immediate trigger, no delay',
    side: 'current',
    created_at: '2025-03-02T10:00:00Z',
  },
  {
    id: 'demo-ann-6',
    audit_section_id: 'demo-section-6',
    asset_id: 'demo-asset-4',
    x_position: 50,
    y_position: 30,
    label: 'Multi-step with personalization',
    side: 'optimized',
    created_at: '2025-03-02T10:00:00Z',
  },
];

export const DEMO_INDUSTRY_EXAMPLES: IndustryExample[] = [
  {
    id: 'example-1',
    industry: 'Beauty / Cosmetics',
    email_type: 'welcome',
    title: 'Glow Recipe Welcome Flow',
    image_url: 'https://images.pexels.com/photos/3685530/pexels-photo-3685530.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['welcome', 'beauty', 'onboarding', 'brand-story'],
    notes: 'Clean, product-focused welcome with skin quiz CTA. Drives engagement and zero-party data collection.',
  },
  {
    id: 'example-2',
    industry: 'Beauty / Cosmetics',
    email_type: 'promotional',
    title: 'Drunk Elephant Product Launch',
    image_url: 'https://images.pexels.com/photos/3762879/pexels-photo-3762879.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['promotion', 'launch', 'beauty', 'premium'],
    notes: 'Minimalist product launch email with strong visual hierarchy and single CTA.',
  },
  {
    id: 'example-3',
    industry: 'Beauty / Cosmetics',
    email_type: 'post-purchase',
    title: 'Glossier Post-Purchase Education',
    image_url: 'https://images.pexels.com/photos/3735218/pexels-photo-3735218.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['post-purchase', 'education', 'beauty', 'retention'],
    notes: 'Educational post-purchase email with usage tips and complementary product suggestions.',
  },
  {
    id: 'example-4',
    industry: 'Horticulture / Plants',
    email_type: 'welcome',
    title: 'The Sill Welcome Series',
    image_url: 'https://images.pexels.com/photos/4505166/pexels-photo-4505166.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['welcome', 'plants', 'educational', 'lifestyle'],
    notes: 'Warm, educational welcome that introduces the brand mission and guides to first purchase with plant quiz.',
  },
  {
    id: 'example-5',
    industry: 'Horticulture / Plants',
    email_type: 'educational',
    title: 'Bloomscape Care Guide Series',
    image_url: 'https://images.pexels.com/photos/4503273/pexels-photo-4503273.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['education', 'plants', 'care-guide', 'retention'],
    notes: 'Post-purchase care guide email that builds brand trust and reduces returns.',
  },
  {
    id: 'example-6',
    industry: 'Horticulture / Plants',
    email_type: 'seasonal',
    title: 'Spring Collection Launch',
    image_url: 'https://images.pexels.com/photos/1084199/pexels-photo-1084199.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['seasonal', 'plants', 'collection', 'promotional'],
    notes: 'Seasonal collection email with lifestyle photography and urgency elements.',
  },
  {
    id: 'example-7',
    industry: 'Clothing & Apparel',
    email_type: 'welcome',
    title: 'Everlane Welcome + Values',
    image_url: 'https://images.pexels.com/photos/5709661/pexels-photo-5709661.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['welcome', 'apparel', 'brand-story', 'transparency'],
    notes: 'Transparent pricing and brand values lead in this welcome email that builds trust before pushing products.',
  },
  {
    id: 'example-8',
    industry: 'Clothing & Apparel',
    email_type: 'promotional',
    title: 'Outdoor Voices Campaign Email',
    image_url: 'https://images.pexels.com/photos/6311392/pexels-photo-6311392.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['promotion', 'apparel', 'lifestyle', 'community'],
    notes: 'Lifestyle-forward promotional email that sells a feeling rather than just a discount.',
  },
  {
    id: 'example-9',
    industry: 'Clothing & Apparel',
    email_type: 'post-purchase',
    title: 'Allbirds Cross-Sell Email',
    image_url: 'https://images.pexels.com/photos/5710151/pexels-photo-5710151.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['post-purchase', 'apparel', 'cross-sell', 'recommendation'],
    notes: 'Smart post-purchase cross-sell based on purchase history with complementary product recommendations.',
  },
  {
    id: 'example-10',
    industry: 'Manufacturing / B2B',
    email_type: 'welcome',
    title: 'Industrial Supply Welcome',
    image_url: 'https://images.pexels.com/photos/3862634/pexels-photo-3862634.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['welcome', 'b2b', 'professional', 'onboarding'],
    notes: 'Professional welcome email that establishes expertise and guides to key product categories.',
  },
  {
    id: 'example-11',
    industry: 'Manufacturing / B2B',
    email_type: 'educational',
    title: 'Technical Specification Guide',
    image_url: 'https://images.pexels.com/photos/3862627/pexels-photo-3862627.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['education', 'b2b', 'technical', 'guide'],
    notes: 'Technical content email that provides value and positions the brand as a trusted resource.',
  },
  {
    id: 'example-12',
    industry: 'Manufacturing / B2B',
    email_type: 'promotional',
    title: 'B2B Reorder Reminder',
    image_url: 'https://images.pexels.com/photos/4483610/pexels-photo-4483610.jpeg?auto=compress&cs=tinysrgb&w=600',
    tags: ['promotion', 'b2b', 'reorder', 'automation'],
    notes: 'Data-driven reorder reminder based on purchase cycle analysis. High conversion rate for consumable products.',
  },
];

export const DEMO_USER = {
  id: 'demo-user',
  name: 'Emil G',
  email: 'emil@ecdigitalstrategy.com',
  role: 'admin' as const,
  created_at: '2025-01-01T00:00:00Z',
};

export const DEMO_ACTIVITY = [
  { id: '1', action: 'Published audit report', target: 'Luxe Glow Beauty', user: 'Emil G', time: '2 hours ago' },
  { id: '2', action: 'Completed section review', target: 'Flows Audit - Luxe Glow', user: 'Emil G', time: '3 hours ago' },
  { id: '3', action: 'Started new audit', target: 'Bloom & Petal', user: 'Marcus Kim', time: '1 day ago' },
  { id: '4', action: 'Added client', target: 'ThreadCraft Apparel', user: 'Emil G', time: '2 days ago' },
  { id: '5', action: 'Ran AI analysis', target: 'Luxe Glow Beauty Audit', user: 'Emil G', time: '3 days ago' },
  { id: '6', action: 'Uploaded screenshots', target: 'ThreadCraft - Campaign Review', user: 'Marcus Kim', time: '4 days ago' },
];

export const DEMO_FLOW_PERFORMANCE: FlowPerformance[] = [
  {
    id: 'fp-1',
    audit_id: 'demo-audit-1',
    flow_name: 'Abandoned Cart',
    flow_status: 'live',
    priority: 'high',
    recipients_per_month: 1980,
    actual_open_rate: 28.4,
    benchmark_open_rate_low: 40,
    benchmark_open_rate_high: 50,
    actual_click_rate: 1.2,
    benchmark_click_rate_low: 10,
    benchmark_click_rate_high: 15,
    actual_conv_rate: 0.28,
    benchmark_conv_rate_low: 5,
    benchmark_conv_rate_high: 10,
    monthly_revenue_current: 890,
    monthly_revenue_opportunity: 2800,
    notes: 'Single email, no discount ladder, generic copy. Triggers 2 hours after abandonment — too fast. Missing urgency elements and product imagery.',
  },
  {
    id: 'fp-2',
    audit_id: 'demo-audit-1',
    flow_name: 'Welcome Series',
    flow_status: 'live',
    priority: 'high',
    recipients_per_month: 1240,
    actual_open_rate: 52.1,
    benchmark_open_rate_low: 45,
    benchmark_open_rate_high: 60,
    actual_click_rate: 1.1,
    benchmark_click_rate_low: 8,
    benchmark_click_rate_high: 15,
    actual_conv_rate: 0.41,
    benchmark_conv_rate_low: 2,
    benchmark_conv_rate_high: 5,
    monthly_revenue_current: 490,
    monthly_revenue_opportunity: 1850,
    notes: 'Two emails only. Email #1 performs well but email #2 drops to <0.5% click. No brand story, no social proof sequence, no preference collection.',
  },
  {
    id: 'fp-3',
    audit_id: 'demo-audit-1',
    flow_name: 'Browse Abandonment',
    flow_status: 'missing',
    priority: 'critical',
    recipients_per_month: 0,
    actual_open_rate: null,
    benchmark_open_rate_low: 35,
    benchmark_open_rate_high: 45,
    actual_click_rate: null,
    benchmark_click_rate_low: 5,
    benchmark_click_rate_high: 10,
    actual_conv_rate: null,
    benchmark_conv_rate_low: 1,
    benchmark_conv_rate_high: 3,
    monthly_revenue_current: 0,
    monthly_revenue_opportunity: 1800,
    notes: 'Not currently set up. With 120K monthly visitors and a 45K list, this is the easiest flow to implement and generates immediate results.',
  },
  {
    id: 'fp-4',
    audit_id: 'demo-audit-1',
    flow_name: 'Post-Purchase',
    flow_status: 'missing',
    priority: 'critical',
    recipients_per_month: 0,
    actual_open_rate: null,
    benchmark_open_rate_low: 45,
    benchmark_open_rate_high: 55,
    actual_click_rate: null,
    benchmark_click_rate_low: 6,
    benchmark_click_rate_high: 12,
    actual_conv_rate: null,
    benchmark_conv_rate_low: 3,
    benchmark_conv_rate_high: 7,
    monthly_revenue_current: 0,
    monthly_revenue_opportunity: 2400,
    notes: 'No post-purchase sequence at all. Every buyer should receive usage tips, review requests, and cross-sell recommendations.',
  },
  {
    id: 'fp-5',
    audit_id: 'demo-audit-1',
    flow_name: 'Winback / Re-engagement',
    flow_status: 'draft',
    priority: 'high',
    recipients_per_month: 0,
    actual_open_rate: null,
    benchmark_open_rate_low: 20,
    benchmark_open_rate_high: 30,
    actual_click_rate: null,
    benchmark_click_rate_low: 2,
    benchmark_click_rate_high: 5,
    actual_conv_rate: null,
    benchmark_conv_rate_low: 1,
    benchmark_conv_rate_high: 3,
    monthly_revenue_current: 0,
    monthly_revenue_opportunity: 980,
    notes: 'A draft winback exists but was never activated. Estimated 12,000 inactive subscribers could be re-engaged.',
  },
  {
    id: 'fp-6',
    audit_id: 'demo-audit-1',
    flow_name: 'Back-in-Stock',
    flow_status: 'missing',
    priority: 'medium',
    recipients_per_month: 0,
    actual_open_rate: null,
    benchmark_open_rate_low: 55,
    benchmark_open_rate_high: 65,
    actual_click_rate: null,
    benchmark_click_rate_low: 10,
    benchmark_click_rate_high: 20,
    actual_conv_rate: null,
    benchmark_conv_rate_low: 5,
    benchmark_conv_rate_high: 12,
    monthly_revenue_current: 0,
    monthly_revenue_opportunity: 640,
    notes: 'Several hero SKUs go out of stock regularly. A back-in-stock flow would capture high-intent buyers at peak interest.',
  },
  {
    id: 'fp-7',
    audit_id: 'demo-audit-1',
    flow_name: 'Sunset / List Cleaning',
    flow_status: 'missing',
    priority: 'medium',
    recipients_per_month: 0,
    actual_open_rate: null,
    benchmark_open_rate_low: 10,
    benchmark_open_rate_high: 20,
    actual_click_rate: null,
    benchmark_click_rate_low: 1,
    benchmark_click_rate_high: 3,
    actual_conv_rate: null,
    benchmark_conv_rate_low: 0,
    benchmark_conv_rate_high: 1,
    monthly_revenue_current: 0,
    monthly_revenue_opportunity: 0,
    notes: 'No sunset flow means unengaged contacts accumulate, dragging down deliverability metrics for the entire account.',
  },
];

export const DEMO_HEALTH_SCORES: HealthScoreItem[] = [
  { category: 'Flow Coverage', score: 2, max_score: 10, status: 'bad', note: 'Only 2 of 7 core flows active. Missing browse abandonment, post-purchase, winback, and back-in-stock.' },
  { category: 'Conversion Rates', score: 2, max_score: 10, status: 'bad', note: 'Flows converting at 0.28-0.41% vs. 2-10% benchmark. 5-25x below industry standard.' },
  { category: 'Click-Through Rates', score: 3, max_score: 10, status: 'bad', note: 'All flows at 1.1-1.2% click rate vs. 8-15% benchmark. Content and CTA treatment needs overhaul.' },
  { category: 'Open Rates', score: 6, max_score: 10, status: 'warning', note: 'Opens are decent but partly inflated by Apple MPP. Not a reliable metric alone.' },
  { category: 'Segmentation', score: 3, max_score: 10, status: 'bad', note: '78% of campaign sends go to "All Subscribers". No engagement-based tiers or RFM segments.' },
  { category: 'Email Design', score: 5, max_score: 10, status: 'warning', note: 'Templates are functional but CTAs are below the fold on mobile. No dynamic content blocks.' },
  { category: 'Signup Forms', score: 2, max_score: 10, status: 'bad', note: 'Converting at 1.2% vs. 5-7% benchmark. Immediate trigger, single-step, no exit-intent.' },
  { category: 'Campaign Strategy', score: 4, max_score: 10, status: 'warning', note: '90% promotional, no content calendar, no A/B testing program. Discount fatigue risk.' },
  { category: 'List Health', score: 5, max_score: 10, status: 'warning', note: 'Deliverability at 94.2%. No sunset flow means inactive segment growing unchecked.' },
  { category: 'Revenue Attribution', score: 4, max_score: 10, status: 'warning', note: 'Flows drive only 12% of email revenue vs. 35-45% benchmark for DTC beauty brands.' },
];

export const DEMO_RECOMMENDATIONS: Recommendation[] = [
  {
    id: 'rec-1',
    audit_id: 'demo-audit-1',
    tier: 'quick_win',
    title: 'Set up Browse Abandonment flow',
    impact: '$1,800/mo',
    effort: '1–2 days',
    description: 'This is a copy-paste from your existing cart flow with a modified trigger. Use product imagery, keep it 2–3 emails, no discount in email #1.',
    sort_order: 1,
  },
  {
    id: 'rec-2',
    audit_id: 'demo-audit-1',
    tier: 'quick_win',
    title: 'Fix popup timing — add 8-second delay',
    impact: '+240 subs/mo',
    effort: '30 minutes',
    description: 'Current popup fires immediately. Changing to an 8-second delay typically lifts conversion 2–3x with zero design changes. Also add exit-intent trigger.',
    sort_order: 2,
  },
  {
    id: 'rec-3',
    audit_id: 'demo-audit-1',
    tier: 'quick_win',
    title: 'Expand Abandoned Cart to 3 emails',
    impact: '+$1,200/mo',
    effort: '2–3 days',
    description: 'Add a second email at 24 hours and a third at 72 hours with a 10% discount. The discount ladder (none → social proof → small offer) is the proven framework.',
    sort_order: 3,
  },
  {
    id: 'rec-4',
    audit_id: 'demo-audit-1',
    tier: 'medium',
    title: 'Build Post-Purchase flow (6 emails over 30 days)',
    impact: '$2,400/mo',
    effort: '1–2 weeks',
    description: 'Order confirmation → usage tips (day 3) → review request (day 7) → product education (day 14) → cross-sell (day 21) → loyalty nudge (day 30). Split by product line.',
    sort_order: 4,
  },
  {
    id: 'rec-5',
    audit_id: 'demo-audit-1',
    tier: 'medium',
    title: 'Rebuild Welcome Series (5 emails)',
    impact: '+$1,360/mo',
    effort: '1 week',
    description: 'Current 2-email series is leaving 75% of potential welcome revenue uncaptured. Add brand story, skin quiz CTA, hero product social proof, and a first-purchase offer at email #5.',
    sort_order: 5,
  },
  {
    id: 'rec-6',
    audit_id: 'demo-audit-1',
    tier: 'medium',
    title: 'Implement engagement-based campaign segmentation',
    impact: '+18% open rate',
    effort: '3–4 days',
    description: 'Create 4 engagement tiers: 30-day active, 60-day, 90-day, and 120-day+. Reduce send frequency progressively. Typically improves overall open rate 15–25% within 30 days.',
    sort_order: 6,
  },
  {
    id: 'rec-7',
    audit_id: 'demo-audit-1',
    tier: 'strategic',
    title: 'Launch a full Winback + Sunset sequence',
    impact: '$980/mo + deliverability',
    effort: '2–3 weeks',
    description: 'Build a 60/90/120-day winback sequence with escalating offers, followed by a hard sunset at 180 days. Removing truly inactive subscribers typically lifts deliverability to 98%+.',
    sort_order: 7,
  },
  {
    id: 'rec-8',
    audit_id: 'demo-audit-1',
    tier: 'strategic',
    title: 'Redesign email templates (mobile-first)',
    impact: '+25% CTR',
    effort: '3–4 weeks',
    description: 'Move CTAs above the fold, switch to modular template system, add dynamic product recommendation blocks. Redesign for mobile-first — 68% of your subscribers open on mobile.',
    sort_order: 8,
  },
  {
    id: 'rec-9',
    audit_id: 'demo-audit-1',
    tier: 'strategic',
    title: 'Build a skin quiz for zero-party data collection',
    impact: 'Long-term LTV',
    effort: '4–6 weeks',
    description: 'A 3-question skin quiz in the welcome flow drives product recommendations and zero-party data. Top beauty brands using quiz-based personalization see 2–3x email revenue per subscriber.',
    sort_order: 9,
  },
];
