// A compact e-commerce UI/UX + conversion knowledge base shared by the web-audit
// agents (findings + "after" image generation). It encodes the standard,
// shopper-familiar layout of each storefront page plus the common anti-patterns
// to avoid, so generated concepts follow real conventions instead of inventing
// odd structures (e.g. two stacked product images with carousel arrows between).

export type WebPageKind = "homepage" | "product" | "collection" | "cart";

export const GENERAL_LAYOUT_RULES = [
  "Follow standard, conventional e-commerce layouts that shoppers already recognize. Never invent unusual or experimental structures.",
  "Never duplicate a section or element: show each image, heading, button, or block once. Never stack two copies of the same image, and never place carousel arrows between two separate images.",
  "Never add a second headline or subheadline. There must be exactly one headline and at most one subheadline in the hero. If the copy needs to change, EDIT the existing text in place, do not keep the old line and add a new one above or below it.",
  "Improve elements in place. If the page already has something a fix refers to (category shortcuts, a search bar, reviews, a menu), enhance the existing one; never add a second duplicate copy of it.",
  "All buttons must be a solid, flat, single brand-color fill with legible text. Never give a button stripes, patterns, textures, gradients, noise, or a see-through fill.",
  "Actually apply positioning fixes: if a fix says elements overlap or a row is cramped (e.g. a floating chat or loyalty button covering other content), visibly move them apart in the redesign so the fix is clearly shown.",
  "MOVING IS NOT COPYING. When a fix says to move, relocate, reposition, or restack an element, that element must appear EXACTLY ONCE in your output, in its new position only. You MUST erase it from its original position and cleanly fill that space with the background behind it. Never leave the original behind, which would duplicate the element and leave the original problem in place.",
  "ADDING MEANS VISIBLE. When a fix says to add an element (a notify-me or email signup button, a star rating, a trust line, a shipping note), that element must be clearly drawn and legible in the output, near the spot the fix names. Do not skip it and do not merely leave room for it.",
  "FITTING TO ONE ROW MEANS ONE ROW, and here is exactly how to do it. When a fix says a navigation or button row should fit on a single line: keep AT MOST 6 top-level links on that line, replace the rest with ONE short menu label such as 'More', and move every link that was sitting on the second row (for example a trailing 'Shop By Brands') either into that menu or onto the single line if it fits. The second row must be COMPLETELY GONE, with no leftover link, no centered orphan text, and no empty band where it used to be: close that vertical space up so the row sits directly above the content below it. Before you finish, look at the navigation and count the lines of links. If you can see two, you have not done the fix.",
  "When a fix is about overlapping or cramped floating widgets (chat bubble, rewards or loyalty badge, back-to-top button), the finished image must show each of those widgets exactly ONCE, fully separated with clear space between them, and none of them touching, stacking on, or covering each other or any content. Check every corner of the output: if any two floating icons still overlap anywhere, the fix has not been applied.",
  "Only change what the fixes require. When NO fix mentions them, leave global elements (the header, navigation, announcement bar, and footer) exactly as in the original screenshot so they stay consistent across pages.",
  "BUT AN EXPLICIT FIX ALWAYS WINS OVER THAT CONSISTENCY RULE. If any fix targets the header, the navigation, or the announcement bar, you MUST apply it fully and visibly in this image. Never return that area untouched because it is a global element: handing back an identical header when a fix asked you to change it is a failed result, not a safe one.",
  "AN ANNOUNCEMENT BAR IS ONE LINE. If its text wraps onto a second line, fit it onto one: shorten the wording or reduce the text size a little. Never leave a two-line announcement bar eating the top of the screen.",
  "Keep one clear visual flow down the page, with related things grouped and consistent spacing and alignment.",
  "One primary action per screen; anything secondary must clearly look secondary.",
  "CALM BEATS COMPLETE. The redesign must look at least as uncluttered and spacious as the original. NEVER shrink the type, tighten the line spacing, or squeeze blocks together to fit more content on screen, and never stack many small new elements one after another. Text stays the same size or larger, and spacing stays the same or more generous. If applying every fix would crowd the screen, apply the most important ones properly and leave the rest out: a calm page that shows three fixes well is far better than a cramped one that shows six badly. This matters most on a phone, where a busy screen is itself a conversion problem.",
  "DO NOT REPEAT INFORMATION THAT IS ALREADY ON SCREEN. Before adding any line of text, check the rest of the image: if the announcement bar already says 'Free shipping on US orders $100+', do not add a second free-shipping line lower down. Do not add a caption that just restates what a nearby button already says (no 'Currently sold out, join the waitlist below' above a button reading 'Notify me when back in stock'). One clear statement of a fact, in one place.",
  "A CENTERED LOGO MEANS A BALANCED HEADER. If the phone header has a centered logo, the icons MUST be split across both sides of it: the menu (and search, if shown) on the LEFT, the logo in the CENTER, the cart on the RIGHT. Never center the logo and then leave every icon bunched on one side with empty space opposite, which looks unfinished and wastes the room centering just freed. Keep the same icons the source has; balancing means repositioning them, not adding or deleting any.",
  "NEVER CHANGE THE SHAPE OF A PRODUCT PHOTO. Whatever aspect ratio the source uses for product imagery, keep it exactly: if the grid cards are square (1:1), every card in your output stays square, on desktop and on phone alike. Do not restretch, letterbox, zoom, or re-crop product photos to fit a new shape, because that slices off part of the product. Change the layout around the images, never the images' proportions.",
  "EVERY PHOTOGRAPH MUST BE THE ORIGINAL ONE, PIXEL FOR PIXEL. Copy each photo across from the source screenshot unchanged. NEVER substitute a different photo, never invent or redraw product imagery, never swap a banner for another scene, and never generate a 'better' looking shot. These are photographs of a real client's real products: a card showing auger blades where the original showed a boxed anchor kit, or a hero showing laid-out parts where the original showed soil, is a fabricated image and completely unusable, no matter how much better it looks. If a fix seems to call for different imagery, describe that in the finding text and leave the photo exactly as it is.",
  "NEVER CROP OR REFRAME A PHOTO, ON ANY DEVICE. Reproduce every photo with the same framing as the original: the same amount of the product in shot, the same margins around it, the same centre point. Do not zoom in, do not tighten the crop to save vertical space on a phone, and do not shift the subject off centre. A plant whose pot or leaves are sliced off, or a product sitting half out of frame, is a failed image even when the layout around it improved. When you need vertical space, take it from padding, headings, or gaps, NEVER from inside a photo.",
  "NEVER REMOVE OR SHRINK THE MAIN PRODUCT PHOTO. On a product page the primary photo stays the largest visual element in the image area, at roughly its original size and position. A row of thumbnails NEVER replaces it: thumbnails stay small and secondary, beside or beneath the main photo. Returning a product page whose big photo is gone, leaving only thumbnails, is a broken result.",
  "ON A PHONE, PRODUCT GRIDS ARE ONE COLUMN. Any grid of product cards in a mobile screenshot must be a single column, ONE product card per row, full width. Never draw a two-across (or tighter) grid of products on a phone: the cards end up too small to read the name, price, and rating. On desktop a multi-column grid is correct.",
  "NEVER change, rewrite, relabel, restyle, move, hide, resize, or remove the location bar under the header that shows 'Growing Zone' and 'Planting in' (you might also think of it as the location bar, personalization bar, or zip/location detector). It is an automatic zip-code-based widget; reproduce it EXACTLY as in the original screenshot, in the same position (including the word 'n/a'). Do not turn it into a prompt like 'Enter your zip', do not add copy to it.",
  "ADD WORDS SPARINGLY. A fix that calls for reassurance, a benefit, or a description is satisfied by ONE short line, not a paragraph and not a bullet list. Never turn a fix into a block of body copy, and never invent bullets of features, care notes, or specs that the source page did not already show. If the source had two lines of copy in a spot, the redesign has about two lines there too.",
  "A NOTIFY-ME OR WAITLIST FIX IS A BUTTON, NOT A FORM. Draw it as a single button in the same style, size, and brand color as the add-to-cart button it stands in for. NEVER draw an inline email input, a form field, or a field-and-button pair on the page: the email is collected in a popup after the tap, so putting the field inline only makes the area look cramped and unfinished.",
  "Every element must look finished and real: aligned, evenly padded, no empty icon slots, no placeholder or label text.",
  "FOLDING SOMETHING AWAY MEANS DELETING IT FROM THE PAGE. When a fix says to fold, merge, move, collapse or tuck an element into the menu, the footer, or anywhere else off screen, that element must be GONE from the visible layout, and everything below it must move up to close the gap. A phone-number strip told to fold into the menu must NOT still be a full-width bar under the header. Leaving it where it was while claiming it moved is the most common way these edits fail. You do not need to show it in its new home, because a closed menu is not visible anyway: just remove it cleanly.",
  // One rule per line. These used to be space-joined into a single paragraph
  // thousands of characters long, where a specific constraint (photo shape,
  // cart anchoring) was just another clause in the middle of a wall of text.
].map((rule) => `  - ${rule}`).join("\n");

// Guardrails for the FINDINGS agent so it doesn't fight standard conventions or
// recommend things the page already has.
export const FINDINGS_GUARDRAILS = [
  "Every finding MUST be a genuine improvement opportunity with a concrete change to make. NEVER submit a finding that just praises something or says to keep it as is (no 'this works well, keep it', no 'no change needed'). Positive observations belong in the strengths (pros) list, not in findings.",
  "A hamburger / collapsed menu on phones is the STANDARD, correct pattern. Never flag it as a problem, and never say category shortcuts should be visible without opening the menu.",
  "Never recommend adding an element the page already has. Look at the screenshot first: if category shortcuts, a search bar, reviews, or similar already exist, either leave them or suggest improving the existing one, do not suggest adding a duplicate.",
  "Header suggestions should be tasteful reorganizations (simplify a cramped header, center the logo, move a non-shopping icon like account into the menu), not blanket complaints that the menu is hidden.",
  "OFF LIMITS: the location bar under the header showing 'Growing Zone' and 'Planting in' (however you would describe it: location fields, location detector, personalization bar, zip bar, region selector). It is automatic zip-code-based detection and 'n/a' before a zip is entered is expected. NEVER write a finding about it in any form: do not call it broken, empty, or unfinished, do not say it wastes space or sits too high, and do not suggest moving, hiding, shrinking, relocating, or removing it. Say nothing about it at all.",
  "Only judge what you can actually SEE in the screenshot. These are above-the-fold shots, so content continues below the crop. NEVER write a finding about something being cut off, truncated, or missing at the bottom edge of the image, and never speculate about what is or is not further down the page. In particular, a horizontal row (category pills, product cards, a carousel) that runs past the right or bottom edge of the crop is normal scrollable content, not a defect: do not claim only N items are visible or that the row 'gets cut off'.",
  "NEVER CLAIM ABSENCE for anything that could simply sit below the crop. Do not write 'there is no X', 'X is missing', 'the page lacks X', or 'shoppers have no X' about reviews, star ratings, descriptions, specs, shipping or returns messaging, guarantees, trust badges, related products, or similar content that normally lives further down a page. You cannot see whether it exists. If placement is genuinely the point AND the anchor element is fully visible, frame it as placement about the visible area only, for example 'the price sits alone in the visible area, so consider surfacing a star rating beside it', never as a flat claim that the store has none.",
  "A SINGLE FLOATING WIDGET IN A CORNER IS NORMAL, NEVER A FINDING. Every storefront has a chat bubble or similar pinned to a bottom corner, and shoppers expect it. Do NOT flag one for sitting near the hero, close to product content, at the edge of an image, or for 'crowding' the view. The ONLY time floating widgets are worth a finding is when TWO OR MORE stack on or overlap each other, or when one genuinely covers something the shopper needs, such as a button, price, or product name. If neither is true, say nothing about it.",
  "DO flag other genuine, visible layout defects: text overflowing or colliding with another element, and elements that are visibly misaligned or cramped.",
  "PROMISE ONLY WHAT THE REWRITE ACTUALLY DELIVERS. When the fix is to reword a line, the reason you give must be something the new wording visibly achieves. Do not say a line needs 'an explanation' or 'context' and then propose replacement copy that explains nothing, because the reader compares your sentence to the image and sees the gap. Reach for the concrete, visible payoff instead: the line currently wraps onto two rows and the shorter wording fits on one, which gives the rest of the panel room. Space, fit, and clarity are reasons the image can prove.",
  "MATCH THE WORDS TO THE DEVICE. A finding's text must describe ONLY the device it is tagged for. If it is tagged mobile, never mention how it looks on desktop, and vice versa: the reader is looking at one screenshot and a sentence about the other device reads as a mistake. Never write a single finding that narrates both devices in one sentence ('on desktop it does X and on mobile it does Y'). If the issue genuinely differs by device, write two separate findings, each tagged to its own device and describing only that one.",
  "CHECK WHETHER THE ANNOUNCEMENT BAR WRAPS. If its text runs onto a second line, that is worth flagging: it doubles the height of the bar and pushes the hero down. Recommend fitting it on one line by shortening the wording or nudging the text size down slightly, and say the shorter wording you would use.",
  "COUNT THE NAVIGATION ROWS before you describe the navigation. Look at the desktop header and count how many separate lines of menu links there are. If any link (for example a trailing 'Shop By Brands') sits on its own second line below the others, the navigation WRAPS onto two rows: say that plainly, never describe it as 'one tight row', and recommend condensing it to a SINGLE row by shortening labels or grouping the least-shopped categories under one menu so the stray link fits back up. Getting this backwards is a serious error, so check the pixels, not your assumption.",
  "HEADER SPACE ARGUMENTS ARE MOBILE-ONLY. A desktop header has plenty of room, so NEVER claim an account, search, wishlist, or cart icon 'takes prime space' or should be moved or shrunk on desktop; that is fine as is. Only raise header icon crowding for MOBILE, where space is genuinely tight. Tag any such finding as mobile, never desktop or both.",
  "THE FIX FOR A CROWDED PHONE HEADER IS TO BALANCE IT, NOT JUST TO HIDE AN ICON. When several icons are bunched on one side of a mobile header, recommend the standard phone arrangement that shoppers already know: the menu (and search, if it stays) on the LEFT, the logo CENTERED, and the cart on the RIGHT. Spreading the icons across both sides uses the space either side of the centered logo and instantly feels less cramped. Only suggest tucking a low-traffic icon such as account into the menu as a SECOND step, after that rebalance, and never suggest hiding search or cart.",
  "SINGLE-OPTION SELECTORS ARE OFF LIMITS ENTIRELY. If the size or variant selector shows only one value, that is almost certainly the only variant the product has, which is normal and needs no attention at all. Write NO finding about it: not about adding more sizes or variants, not about upselling a bigger version, and not about how it is styled, whether it looks selected, active, inactive, greyed out, or 'broken'. With one option there is nothing for the shopper to choose, so its appearance does not matter. You cannot see the catalog, only the page. The same goes for stock: an out-of-stock product is a merchandising fact, not a page defect, so only comment on how clearly the page HANDLES it (a visible notice, a notify-me option, a link to alternatives) if those areas are actually visible.",
  "NEVER RECOMMEND REPEATING SOMETHING THE PAGE ALREADY SAYS. Read the whole screenshot before proposing new copy. If the announcement bar already promises free shipping, do NOT recommend adding a free-shipping line near the buy button; if a reassurance is genuinely needed there, pick something the page does not already state (returns, a guarantee, delivery timing). Equally, never recommend a label that restates an adjacent button, such as a 'currently sold out, join the waitlist' line above a 'Notify me when back in stock' button. Say each thing once.",
  "PROTECT THE BREATHING ROOM, ESPECIALLY ON PHONES. A calm page converts better than a full one, so weigh what a fix COSTS in space against what it gains. Prefer fixes that reword, restyle, or move something already there over fixes that add another element, and never propose several new lines or blocks for the same screen. If a page would need a lot of additions, recommend only the highest-impact one or two and say what should be tightened or removed to make room.",
  "A SLIDE CART SLIDES IN FROM THE RIGHT AND STAYS THERE. On desktop the drawer is a panel pinned to the RIGHT edge, roughly a third of the width, with the page still visible behind it, usually dimmed. NEVER centre it, never turn it into a modal or a full-width sheet, and never blank out or delete the page behind it. The two-panel look, store on the left and cart on the right, is the whole point of a drawer, so returning a centred box floating on an empty background is a failed image no matter how good the cart content is. On a phone the drawer covers the screen, which is normal.",
  "ON A COLLECTION PAGE, CHECK EVERY CARD FOR THE FOUR ESSENTIALS AND FOR A QUICK ADD. Each product card should carry an image, the product NAME, the PRICE, and a star rating, and the grid should offer a quick add-to-cart (an 'Add to cart' or '+' control on the card, or one that appears on hover). If any of those is missing from the cards you can actually see, that IS worth a finding, and a missing quick add is its own finding: without it every shopper must open a product page to buy, which costs a click on the highest-intent action on the page. This is the one place where naming an absence is allowed, because a product card is a self-contained unit and you can see the whole card, unlike content that might sit below the fold. Say which of the four is missing, and recommend the quick add sits on the card without pushing the grid taller (reveal on hover on desktop, a compact button on phones).",
  "A CART UPSELL WITHOUT A QUICK ADD IS A WASTED ROW. If the cart or slide drawer shows a 'You may also like' / recommended products row, check whether each suggestion has a way to add it right there: a small Add button, a plus control, or a tappable price chip. If the suggestions are only an image, a name and a price, say so and recommend a compact add control on each one, because a shopper who has to leave the cart to open a product page usually just checks out without the extra item, which is the whole point of the row. Keep the fix within the cart's space budget: the control belongs ON the existing suggestion row, a small button or a plus beside the price, never a new line under each product and never anything that makes the drawer taller.",
  "A CART FIX MUST NEVER COST A ROW. Every change inside a cart has to fit in the space the original used, or less. If you make an existing line clickable, add a small link, or reword something, it stays on the SAME single row: shorten the wording until it fits rather than letting it wrap to a second line. A fix that makes the drawer taller than it was has made the cart worse, whatever it added.",
  "KEEP THE CART COMPACT. The cart, and especially the slide-out cart drawer, must stay short so the checkout button stays in easy reach. NEVER recommend adding an explanatory sentence, a reassuring paragraph, or extra copy lines to the cart: that pushes checkout further away and costs more than it gains. If something in the cart genuinely needs clarifying, recommend REWORDING the existing line in place, or a tiny inline badge or icon, never a new line of text. Prefer fixes that REMOVE or tighten cart content over any that add to it.",
  "NEVER FABRICATE NUMBERS IN RECOMMENDED COPY. When a fix proposes concrete copy containing a rating, review count, customer count, delivery time or price, use ONLY numbers visible on the page in the screenshots, or phrase the copy without specific numbers ('loved by thousands of gardeners', 'join our happy customers'). A recommendation reading 'Rated 4.8 by 2,000+ gardeners' for a store whose page shows neither number becomes a fabricated claim in the client's concept image, which is worse than no fix at all.",
  "RATINGS THE PAGE DOES NOT SHOW ARE ADVICE, NOT A PICTURE. Recommending star ratings, review counts or customer-count claims is fine ONLY as report advice (install or surface the reviews app, pull real counts into the theme) when the screenshots show no rating data; the concept image cannot draw a rating the store does not have without fabricating it, so such fixes are deliberately left out of the image. When the page DOES show a real rating or count, quote that exact number in the fix so the image can carry it faithfully.",
  "Do not nitpick things that follow standard e-commerce and platform conventions. Focus on changes that genuinely help shoppers.",
// One rule per line, not one paragraph. These were joined with a single space,
// so 24 separate guardrails arrived at the model as a single wall of prose under
// a heading that promises a list. The same flattening was why the photo rules in
// GENERAL_LAYOUT_RULES kept getting ignored until it was fixed there.
].map((rule) => `- ${rule}`).join("\n");

// Sharper CRO heuristics for the FINDINGS agent, distilled for e-commerce
// storefronts. These make the recommendations more specific (headline, button
// copy, trust placement, objection handling) without changing the founder voice.
export const CRO_HEURISTICS = [
  "The 5-second test: a first-time visitor should grasp what the store sells and why it is for them within about five seconds of the page loading. If the hero fails this, that is the highest-priority fix.",
  "Speak in the shopper's benefit language, not internal jargon or clever slogans. Say what they get, not just what the product is.",
  "Headlines win on specificity: concrete outcomes, real numbers, or a clear 'get X without Y' promise beat a vague brand tagline.",
  "Button copy should signal the value of the next step, not a generic action. Prefer 'Shop best sellers' or 'Find my plant' over 'Shop now' or 'Submit'.",
  "Place trust and proof where decisions happen: put star ratings, review counts, and short testimonials right near the buy button and immediately after any benefit claim, not only in a separate section far down.",
  "Handle the obvious objections at the point of purchase: shipping cost and speed, returns, sizing or fit, and guarantees belong near the add-to-cart button, not buried in the footer.",
].join(" ");

export const LAYOUT_BRIEF: Record<WebPageKind, string> = {
  homepage:
    "HOMEPAGE layout: a slim announcement bar (an offer plus a link to act), a clean header (on desktop: logo, search, account, cart; on a phone the standard arrangement is menu and search on the LEFT, logo CENTERED, cart on the RIGHT, so the icons are balanced either side rather than bunched on one), ONE hero with a clear headline, a single primary button, and text that stays legible over any photo (add a dark scrim if needed), then quick category shortcuts, social proof (star ratings or a customer quote), and featured products.",
  product:
    "PRODUCT PAGE layout: exactly ONE image area, either a single main photo with a small thumbnail strip, OR one carousel with small dots. NEVER show two stacked images, and NEVER put carousel arrows between two separate images. Next to the image (desktop) or below it (phone): the product title, the price, a star rating with review count directly under the title, ONE clear add-to-cart button, and a short trust/shipping line. KEEP THE BUY AREA SHORT: at most ONE line of description above the buy button, and never invent a bullet list of features, care notes, or specs that the original page did not already show. Long copy pushes the buy button off the screen, which costs more than the copy gains. A SOLD-OUT ITEM GETS ONE BUTTON, NOT A FORM: draw a single full-width 'Notify me when available' button in exactly the same style, size, and brand color as the add-to-cart button it replaces. NEVER draw an inline email input, a form field, or a label-plus-field pair next to it: tapping the button opens a popup for the email, so showing the field on the page just makes the area look cramped and unfinished.",
  collection:
    "COLLECTION PAGE layout: a clean, even grid of product cards, each with an image, title, price, and rating, all the same size and structure, and each card complete (never an image with its name or price missing). On DESKTOP use a multi-column grid; on a PHONE use ONE column, a single full-width card per row, so every name, price, and rating stays readable. Simple sort/filter controls at the top and a short category intro line. Do not mix card styles.",
  cart:
    "CART / SLIDE-CART layout: each line item shows a thumbnail, title, chosen variant, price, and a quantity stepper. A clear subtotal, a single prominent checkout button, a free-shipping progress line when relevant, and a short reassurance line (easy returns / secure checkout). An optional 'you may also like' row is fine, shown once, and each suggestion in it carries a compact add control (a small Add button or a plus beside the price) on its existing row, so the item can be added without leaving the cart. STAY COMPACT: the drawer must not get taller than the original. Do not add explanatory sentences or extra copy lines; reword existing lines in place instead, and keep the checkout button visible without scrolling. KEEP IT PINNED RIGHT: on desktop the drawer stays a right-edge panel over the still-visible page, never a centred modal.",
};

/** Page-specific layout brief plus the general layout rules, for prompt injection. */
export function layoutGuidance(kind: WebPageKind): string {
  return `${LAYOUT_BRIEF[kind]}\n${GENERAL_LAYOUT_RULES}`;
}

// Rules for the HTML "after" engine, which EDITS the real page rather than
// repainting it. Deliberately a different, much shorter list than the image
// rules: most of those exist to stop a generative model damaging photos or
// inventing imagery, and on this path that is structurally impossible, so
// repeating them would only dilute what is left. What remains is the judgement
// a real page edit still needs.
export const HTML_AFTER_RULES = [
  "CALM BEATS COMPLETE. The edited page must look at least as uncluttered as the original. Never shrink type or tighten spacing to fit more in, and never stack several small additions in the same area. If showing every fix would crowd the screen, show the most important ones properly.",
  "KEEP THE FIRST FOLD LIGHT, ESPECIALLY ON A PHONE. Do not fill the top of the page with added copy. A product page in particular should not gain paragraphs above the buy button: if a description needs taming, clamp it to a few lines instead of expanding it.",
  "SAY IT ONCE. Never add a line that repeats something already on the page. If the announcement bar already promises free shipping, the hero does not need to.",
  "EDIT COPY IN PLACE RATHER THAN ADDING TO IT. A vague headline should be rewritten with set_text, not left in place with a second headline added under it. An announcement bar that wraps onto two lines should be shortened, not restyled.",
  "A CART FIX MUST NEVER COST A ROW. Inside a cart or slide drawer, every change has to fit the existing space: reword a line, or use a compact control on the row that is already there. The drawer must not get taller and the checkout button must stay visible.",
  "A QUICK ADD BELONGS ON THE ROW IT SERVES. On product cards and cart upsell rows use the compact button variant so the card keeps its height and the photo keeps its shape.",
  "MOVE, DO NOT DUPLICATE. When something is in the wrong place, move it. Never hide it and add a lookalike somewhere else.",
  "ONE PRIMARY ACTION PER SCREEN. If a page has several equal-looking buttons, emphasize the one that matters instead of adding another.",
  "A THIN BAR HAS NO SPARE ROOM. To add a link into an announcement bar that is already full, shorten its wording in the same edit set. Adding to a full bar without shortening it pushes the bar onto a second line, and the edit will be rolled back.",
  "ADDING MEANS VISIBLE. Anchor every addition to an element inside the FIRST FOLD, near the spot the fix names. An element added to an anchor below the crop is not in the concept image at all, and the edit will be marked as not shown.",
  "A HEADER FINDING GETS rebalance_header, nothing else. It rebuilds the header row from the theme's own elements into the standard balanced layout (menu and search left, logo centred, cart right) and verifies itself. Never try to fix a header with move or style: theme CSS either overrides the change or collides the icons, and either way the finding ends up looking ignored in the after.",
  "PROMISE ONLY WHAT THE PAGE CAN BACK UP. Ratings, review counts, delivery times and stock claims must come from what the page already shows. Never invent a number.",
].map((rule) => `- ${rule}`).join("\n");
