import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { requireStaffUserId } from "../_shared/auth.ts";
import {
  buildAuthorizeUrl,
  disconnectPatch,
  keepAliveXero,
  loadConnection,
  serviceClient,
  xeroApi,
  xeroCredentials,
  xeroRedirectUri,
} from "../_shared/xero.ts";

// Admin-facing Xero actions for the Settings panel: check status, start the
// connect flow, list revenue accounts, save which account to post to, and
// disconnect. Also serves the weekly keep-alive, which authenticates with a
// shared secret instead of a user session because cron has no user.

const corsHeaders: Record<string, string> = {
  "access-control-allow-origin": "*",
  "access-control-allow-headers":
    "authorization, x-client-info, apikey, content-type, accept, origin, referer, user-agent, x-xero-cron-secret",
  "access-control-allow-methods": "POST, OPTIONS",
};

function json(data: unknown, init: ResponseInit = {}) {
  return new Response(JSON.stringify(data), {
    headers: { ...corsHeaders, "content-type": "application/json; charset=utf-8", ...(init.headers ?? {}) },
    ...init,
  });
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders });
  if (req.method !== "POST") return json({ ok: false, error: { code: "method_not_allowed" } }, { status: 405 });

  const body = (await req.json().catch(() => ({}))) as { action?: string; account_code?: string; tax_type?: string };
  const action = body.action ?? "status";
  const sb = serviceClient();

  // The cron path is unauthenticated by design (no user session exists), so it
  // is gated on a dedicated secret whose only power is refreshing our token.
  if (action === "keepalive") {
    const provided = req.headers.get("x-xero-cron-secret") ?? "";
    // The secret is generated by and read from Postgres (service-role only), so
    // it never has to be pasted into the cron command or an env var by hand.
    const { data: authRow } = await sb.from("xero_cron_auth").select("secret").eq("id", "default").maybeSingle();
    const expected = ((authRow?.secret as string | undefined) ?? "").trim();
    if (!expected || provided !== expected) {
      return json({ ok: false, error: { code: "forbidden" } }, { status: 403 });
    }
    const result = await keepAliveXero(sb);
    return json({ ok: result.ok, message: result.message });
  }

  let uid: string;
  try {
    uid = await requireStaffUserId(req);
  } catch (e) {
    return json(
      { ok: false, error: { code: "unauthorized", message: e instanceof Error ? e.message : "Unauthorized" } },
      { status: 200 },
    );
  }

  try {
    if (action === "status") {
      const row = await loadConnection(sb);
      let credentialsConfigured = true;
      try {
        await xeroCredentials();
      } catch {
        credentialsConfigured = false;
      }
      return json({
        ok: true,
        connected: Boolean(row?.refresh_token_ciphertext && row?.tenant_id),
        credentials_configured: credentialsConfigured,
        tenant_name: row?.tenant_name ?? null,
        sales_account_code: row?.sales_account_code ?? null,
        tax_type: row?.tax_type ?? null,
        last_refreshed_at: row?.last_refreshed_at ?? null,
        last_error: row?.last_error ?? null,
        redirect_uri: xeroRedirectUri(),
      });
    }

    if (action === "connect") {
      const { clientId } = await xeroCredentials();
      const state = crypto.randomUUID().replace(/-/g, "");
      const { error } = await sb.from("xero_oauth_states").insert({ state, created_by: uid });
      if (error) throw error;
      return json({ ok: true, url: buildAuthorizeUrl(clientId, state) });
    }

    if (action === "accounts") {
      // Revenue accounts only: posting a sale to an expense code is a mistake
      // worth preventing in the picker rather than catching later in Xero.
      const out = await xeroApi<{ Accounts?: Array<Record<string, unknown>> }>(
        sb,
        `/Accounts?where=${encodeURIComponent('Class=="REVENUE"')}`,
      );
      const accounts = (out.Accounts ?? [])
        .map((a) => ({ code: String(a.Code ?? ""), name: String(a.Name ?? ""), taxType: String(a.TaxType ?? "") }))
        .filter((a) => a.code);
      return json({ ok: true, accounts });
    }

    if (action === "save_settings") {
      const { error } = await sb
        .from("xero_connection")
        .upsert({
          id: "default",
          sales_account_code: body.account_code?.trim() || null,
          tax_type: body.tax_type?.trim() || null,
        });
      if (error) throw error;
      return json({ ok: true });
    }

    if (action === "disconnect") {
      const { error } = await sb.from("xero_connection").upsert({ id: "default", ...disconnectPatch() });
      if (error) throw error;
      return json({ ok: true });
    }

    return json({ ok: false, error: { code: "bad_request", message: `Unknown action ${action}` } }, { status: 200 });
  } catch (e) {
    return json(
      { ok: false, error: { code: "request_failed", message: e instanceof Error ? e.message : "Unknown error" } },
      { status: 200 },
    );
  }
});
