-- Zak's updated Master Services Agreement (2026-09-25): adds TCPA and messaging
-- compliance, data housing and sub-processors, AI tool use (Claude), website
-- accessibility, advertising claims, and affiliates. Replaces the catalog text
-- for new proposals; every proposal already sent keeps the text frozen in its
-- contracts_snapshot.
update public.contract_documents
set content = $msa$**Master Services Agreement**

This Master Services Agreement (the “Agreement”) is made and entered into as of the date this Agreement is fully executed as reflected on the signature page (the “Effective Date”), by and between ECD Digital Strategy, a New York limited liability company (“ECD”), with a principal place of business at 1114 Ruffner Rd, Niskayuna, NY 12309, and the client identified on the signature page below (“Client”). ECD and Client are sometimes individually referred to herein as a “Party” and collectively as the “Parties”.

This Agreement, together with (a) any Statements of Work executed by the Parties in accordance with this Agreement, (b) any exhibits hereto, (c) any written amendments to any of the foregoing executed by the Parties, and (d) ECD’s Client Operating Rules (including the Termination & Transition terms set forth therein), is collectively referred to as the “Agreement.”

**1. Definitions**
(a) “Client Materials” means any data or materials provided by Client to ECD that are used in connection with the Services or Service Deliverables, including technical information and functional specifications, user data, logos, photographs, compilations of facts, artwork, animations, video or audio files, raw video footage, music, images, source materials, or other components comprising the Service Deliverables.

(b) “Intellectual Property Rights” means any and all (i) rights associated with works of authorship, including but not limited to copyrights; (ii) trademark and trade name rights and similar rights; (iii) trade secret rights; (iv) patents, patent disclosures, and inventions (whether patentable or not); and (v) all other intellectual property rights in any jurisdiction throughout the world, whether registered or unregistered.

(c) “Person(s)” means an individual, partnership, corporation, limited liability company, association, joint stock company, trust, joint venture, unincorporated organization, governmental entity, or any department, agency, or political subdivision thereof, or any other entity.

(d) “Services” means the digital strategy, e-commerce, web development and design, paid media (including paid social and paid search advertising), email and SMS marketing, retention marketing, conversion rate optimization, site support and maintenance, and any other related consulting and support services set forth in the fully executed SOW(s). For clarity, the Services are strategic, creative, and marketing-platform services and do not include Store-Side Execution within Client’s e-commerce or storefront platform (as defined in ECD’s Client Operating Rules); Client is solely responsible for all Store-Side Execution.

(e) “Service Deliverable(s)” means all documents, work product, site designs, and any other materials to be delivered to Client by ECD in connection with the Services.

(f) “Statement of Work” or “SOW” means a mutually executed agreement by the Parties setting forth the agreed-upon scope of the Services, Service Deliverables, estimated hours and/or work effort, billing rates and other pricing information, and project schedule.

(g) “AI Tools” has the meaning set forth in Section 9(c)(i).

(h) “ECD Platform” means ECD’s proprietary client intelligence, analytics, and reporting platform, as further described in Section 9(b).

(i) “Affiliate” means, with respect to a Party, any Person that directly or indirectly controls, is controlled by, or is under common control with such Party, where “control” means the ownership of more than fifty percent (50%) of the voting equity of such Person, or the power to direct or cause the direction of the management and policies of such Person, whether through ownership of voting securities, by contract, or otherwise.

**2. Services**
ECD agrees to perform the Services as set forth in each applicable SOW. The specific scope, deliverables, timeline, and fees for each engagement will be defined in the applicable SOW, which is incorporated herein by reference.

The Parties’ operational obligations, including workflow, request lead times, approvals, revisions, scheduling, edit locks, and termination and transition mechanics, are set out in ECD’s Client Operating Rules, which are incorporated into and made part of this Agreement by this reference. Client acknowledges that it has received, or has been given access to, the version of the Client Operating Rules in effect as of the Effective Date.

In the event of a conflict or inconsistency among the documents comprising the Agreement, the following order of precedence controls: (1) this Master Services Agreement; (2) the Client Operating Rules; and (3) the applicable SOW. A SOW may vary a term of this Master Services Agreement or of the Client Operating Rules only if the SOW (i) expressly identifies, by section number, the provision being varied, (ii) expressly states that it supersedes that provision, and (iii) is signed by both Parties. A general integration, entire-agreement, “conflicts control,” or similar provision in a SOW is not sufficient to vary this Agreement or the Client Operating Rules. Notwithstanding the foregoing, no SOW may vary Sections 9, 10, 11, 12, or 24 of this Master Services Agreement except by a written amendment executed in accordance with Section 17.

ECD may update the Client Operating Rules from time to time. The version of the Client Operating Rules in effect as of the Effective Date of an applicable SOW governs that SOW for its duration, unless the Parties agree otherwise in writing. ECD will maintain each version of the Client Operating Rules with a version number and effective date, and will provide the operative version to Client upon request. For the avoidance of doubt, an update to the Client Operating Rules is not an amendment of this Agreement for purposes of Section 17 with respect to any SOW then in effect.

**3. Statements of Work**
(a) Changes in SOWs. If a Party requests a change to the terms of a SOW, including changes to the scope of a project or payment schedule, both Parties must approve the change in writing (email is sufficient), except as otherwise provided in this Agreement.

(b) Multiple or Subsequent SOWs. The Parties may execute additional or amended SOWs under this Agreement either contemporaneously with the initial SOW in the event of multiple projects, or after the scope of the Services in the initial SOW is completed, such as for post-project support or retainer agreements. Each new or amended SOW will be governed by the terms of this Agreement.

**4. Payment**
(a) Invoices. ECD will issue to Client an invoice for each payment due and owing, as it comes due (an “Invoice”). All invoices are due on receipt, without set-off or deduction. Upon execution of an SOW, Client will receive an Invoice with a link to pay in accordance with the terms of the SOW. Client’s first payment is due upon receipt, and no Services will commence under the SOW until this deposit is received. Client shall pay ECD in accordance with the terms of the SOW and, if applicable, all reasonable and actual expenses incurred by ECD in performing the Services, including travel, software fees, hosting fees, and tools, subject to Client’s prior written authorization (email is sufficient).

(b) Payment Methods. Except as expressly provided herein, all payments are non-refundable. ECD accepts payment in the form of ACH transfers and GoCardless. If Client chooses to pay via credit card, a 3% processing fee will be added to invoices.

(c) Autopay Authorization. By signing this Agreement, Client authorizes ECD to automatically charge the payment method on file for all amounts due under any executed SOW or agreement, on or after each invoice date. This authorization remains in effect until Client provides ECD with thirty (30) days’ prior written notice of cancellation. ECD will notify Client before processing any payment. Client may amend the payment method on file at any time by providing written notice to ECD.

(d) Late Payment and Remedies. Client’s failure to make payment of any amounts when due under this Agreement shall constitute a material breach. If Client fails to make payment when due, Client agrees: (i) to pay ECD a late charge at a rate of 10% per month on all past-due amounts exceeding 60 days, or the maximum rate permitted by New York State law, whichever is higher; (ii) to reimburse ECD for all reasonable costs and expenses incurred in collecting past-due amounts, including reasonable attorneys’ fees; and (iii) ECD reserves the right to immediately pause all work and communication on the account until the balance is brought current, or to terminate the Agreement. These remedies are not exhaustive and do not limit ECD’s other rights and remedies under this Agreement or applicable law.

**5. Term and Termination**
(a) Term. This Agreement commences as of the Effective Date and continues until terminated by either Party in accordance with this Agreement.

(b) Termination. This Agreement shall continue until the expiration, completion, or termination of all SOW(s), unless earlier terminated in accordance with Section 5(c). Either Party may terminate this Agreement or any SOW at any time by providing thirty (30) days’ written notice to the other Party. All Services will continue through the end of the notice period, and Client agrees to pay for all Services rendered through that date. Notice must be sent via email.

(c) Termination by Breach. If either Party fails to materially comply with any of the terms and conditions of this Agreement (a “Breach”) and such Party fails to correct such Breach within thirty (30) days following written notice thereof (the “Cure Period”) by the other Party (the “Non-Breaching Party”), then such Non-Breaching Party may terminate this Agreement with written notice; provided, however, that the Cure Period shall not apply to a termination for Client’s failure to make timely payments, which is a material breach of this Agreement. If this Agreement is terminated due to either Party’s Breach, Client shall pay ECD all amounts due hereunder with respect to Services performed as of the date of termination, without set-off or deduction.

(d) Effects of Termination. Upon any expiration or termination of this Agreement or any SOW: (a) all rights and access to Client Materials granted to ECD shall immediately terminate; and (b) Client shall immediately pay to ECD all amounts due for the period for which Client contracted, without set-off or deduction. Upon payment of all amounts due and owing hereunder, ECD will provide Client with all Service Deliverables in progress up through the effective date of termination.

(e) Transfer of Materials. Upon termination, provided there is no outstanding indebtedness then owing by Client to ECD, ECD shall transfer, assign, and make available to Client all property and materials in its possession or control belonging to Client. Client agrees to pay all reasonable costs associated with the transfer of materials.

(f) ECD’s Additional Termination Rights. In addition to the rights set forth in Sections 5(b) and 5(c), ECD may terminate this Agreement or any SOW effective immediately upon written notice, and without the Cure Period set forth in Section 5(c), if Client: (i) engages in any unlawful, fraudulent, or non-compliant activity in connection with the Services; (ii) misuses, or directs ECD to misuse, customer or personal data or any third-party platform, or requests any action that would violate applicable law or the terms, policies, or acceptable-use requirements of a third-party platform (including Klaviyo, Shopify, Meta, or Google); (iii) engages in abusive, harassing, or threatening conduct toward ECD’s personnel; (iv) creates a material legal, regulatory, reputational, or platform-compliance risk to ECD; or (v) has a material conflict of interest that cannot reasonably be resolved. ECD may terminate this Agreement or any SOW upon ten (10) days’ written notice if Client fails to cure within such period (i) a repeated or continued failure to provide the cooperation, access, information, approvals, or materials reasonably required for ECD to perform the Services, or (ii) any other material breach reasonably capable of cure within such shortened period. For clarity, termination for Client’s failure to make timely payment remains governed by Sections 4(d) and 5(c) and is not subject to any cure period. Upon termination under this Section 5(f), Client shall pay ECD all amounts due for Services performed through the effective date of termination, together with any fees due under the notice period to the extent applicable, without set-off or deduction.

(g) Post-Termination Access and Data. Following the effective date of termination, ECD will cease accessing Client’s accounts, platforms, and Client Materials, and Client is responsible for revoking ECD’s access to Client platforms. Upon Client’s written request made within thirty (30) days after termination, ECD will return or delete Client data in its possession within a commercially reasonable period, except that ECD may retain (i) copies contained in routine system backups, (ii) records reasonably required for financial, tax, legal, or compliance purposes, and (iii) materials reasonably necessary to establish or defend legal claims. ECD’s retention and use of Aggregated Data remains governed by Section 6(d). The operational steps for access removal, data return, and handover are set out in ECD’s Client Operating Rules. This Section 5(g) shall survive the expiration or termination of this Agreement.

(h) No Post-Handover Responsibility. From and after the handover date (or, if earlier, the effective date of termination), ECD shall have no responsibility or liability for the operation, performance, results, or maintenance of any flows, campaigns, automations, integrations, segments, templates, or other deliverables, including for email or SMS deliverability, revenue, list health, or platform performance, or for any changes, edits, errors, or outcomes arising after that date, whether made by Client, a subsequent service provider, or a third-party platform. This Section 5(h) is in addition to, and does not limit, the disclaimers and limitations in Sections 7, 9, 10, and 11, and shall survive the expiration or termination of this Agreement.

(i) Survival. Sections 4, 5(g), 5(h), 6(c), 6(d), 6(e), 7(a), 8, 9, 10, 11, 12, and 13 will survive any termination or expiration of this Agreement.

**6. Ownership and Copyright**
(a) Client Materials. All right, title, and interest (including all Intellectual Property Rights) in and to the Client Materials are owned by Client; provided, however, that ECD retains the right to save, possess, refer to, rely upon, and re-use any underlying code used or relied upon in completing the Services.

(b) Work Made for Hire. To the fullest extent permitted by law, upon full and complete payment for the Services, ECD will provide or return to Client all underlying data or information given to ECD to perform the Services. ECD acknowledges, and will cause its personnel to agree, that with respect to any Service Deliverable that may qualify as “work made for hire” as defined in 17 U.S.C. § 101, such Service Deliverable is hereby deemed a “work made for hire” for Client. If any Service Deliverable does not constitute a “work made for hire,” ECD hereby irrevocably assigns, and shall cause its personnel to irrevocably assign to Client, in each case without additional consideration, all right, title, and interest throughout the world in and to the Service Deliverable, including all Intellectual Property Rights therein. ECD shall cause its personnel to irrevocably waive, to the extent permitted by applicable law, any and all claims to so-called “moral rights” or rights of droit moral with respect to the Service Deliverables.

(c) Portfolio and Marketing Rights. Client hereby grants ECD the right to use Client’s name and logo(s) for use in ECD’s marketing materials and portfolio, unless Client provides written notice clearly stating its intent to deny ECD this right. This right shall survive the termination of this Agreement.

(d) Aggregated and De-Identified Data. Notwithstanding anything to the contrary in this Agreement (including Section 12), ECD may collect, generate, retain, and use data and information derived from the Client Materials, the Services, and the performance of Client’s marketing programs, provided such data is aggregated and/or de-identified such that it cannot reasonably be used, alone or in combination with other information, to identify Client, any individual, or any specific end customer of Client (collectively, “Aggregated Data”). As between the Parties, ECD owns all right, title, and interest in and to the Aggregated Data. ECD may use Aggregated Data for any lawful business purpose, including to operate, analyze, improve, benchmark, and develop its services, products, tools, models, and systems (including machine learning and artificial intelligence systems). ECD shall not (i) disclose Aggregated Data to any third party in a form that identifies Client or discloses Client’s pricing or other Confidential Information, or (ii) attempt to re-identify any de-identified data. ECD shall handle all such data in compliance with applicable privacy and data protection laws. This Section 6(d) shall survive the expiration or termination of this Agreement.

(e) ECD Retained Materials. Notwithstanding Section 6(b), ECD exclusively owns and retains all right, title, and interest (including all Intellectual Property Rights) in and to all materials, know-how, and property that are created, developed, or acquired by ECD independently of the Services, or that are of general application and reusable across ECD’s clients, including without limitation ECD’s pre-existing materials, frameworks, methodologies, processes, systems, workflows, templates, playbooks, standard operating procedures, tools, software, code, the ECD Platform, and generic or non-Client-specific components (collectively, “ECD Materials”). To the extent any ECD Materials are incorporated into, or are necessary to the use of, a Service Deliverable, ECD grants Client a non-exclusive, royalty-free, worldwide, perpetual license to use such ECD Materials solely as embedded within, and solely for Client’s use of, the paid Service Deliverables. No title to or ownership of any ECD Materials transfers to Client, and nothing in this Agreement (including the work-made-for-hire and assignment provisions of Section 6(b)) shall be construed to assign or transfer any ECD Materials to Client. This Section 6(e) shall survive the expiration or termination of this Agreement.

**7. Representations and Warranties**
(a) Disclaimer. EXCEPT AS SET FORTH IN SECTION 7(B) AND EXCEPT FOR ANY EXPRESS WARRANTIES SET FORTH IN THIS AGREEMENT AND ANY SOW, THE SERVICES ARE PROVIDED ON AN “AS IS” BASIS AND EACH PARTY DISCLAIMS ANY REPRESENTATIONS, WARRANTIES, COVENANTS, OR CONDITIONS OF ANY KIND OR NATURE (EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE), INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.

(b) ECD Warranties. ECD represents and warrants that the Services provided under this Agreement (including any Service Deliverables): (i) will not infringe on the Intellectual Property Rights of any third party or any rights of publicity or privacy; (ii) will not violate any applicable law, statute, ordinance, or regulation; (iii) will be performed using personnel of required skill, experience, and qualifications in a professional and workmanlike manner; (iv) will not contain any virus, Trojan horse, worm, backdoor, or other harmful code; and (v) will conform in all material aspects with the requirements or specifications stated in this Agreement and the applicable SOW(s). The warranties in this Section 7(b) are given subject to, and are expressly qualified by, Sections 9(c), 9(d), 9(e), and 9(f). Without limiting the foregoing, the warranty in Section 7(b)(ii) does not extend to (A) compliance of any communication, list, or consent record with the TCPA or any other telemarketing, messaging, or consumer protection law or standard, (B) compliance of any website, application, or Service Deliverable with the ADA, Section 508, WCAG, or any other accessibility law, regulation, or standard, or (C) the truth, accuracy, substantiation, or legality of any claim, statement, or material supplied or approved by Client.

**8. Non-Solicitation of ECD Personnel**
Client acknowledges, agrees, and covenants that at all times during the term of this Agreement and for a period of twenty-four (24) months immediately following the termination of this Agreement for any reason, Client shall not, directly or indirectly, hire, retain, solicit, or employ any Person who was an employee or contractor of ECD during the one (1) year period immediately prior to the date of termination of this Agreement, and with whom Client had knowledge of, access to, or contact with while such Person was engaged with ECD. Client shall not cause or request any other Person to do so, or assist others in doing any of the foregoing prohibited acts.

(a) Injunctive Relief. Client acknowledges it would cause ECD serious and irreparable injury if Client were to breach its obligations as set forth in Section 8, and further acknowledges that there is no adequate remedy at law for such violations. Accordingly, Client agrees that ECD shall be entitled to seek one or more preliminary or permanent injunctive orders against Client restraining and enjoining any act which would constitute a threatened or actual breach of the covenants contained in Section 8, without the need of a bond or showing of actual damages. Client agrees that no alleged counterclaim, defense, or offset shall affect or impair ECD’s right to seek injunctive relief.

**9. Compliance with Laws; Data, Artificial Intelligence, Marketing, and Advertising Compliance**
**(a) Compliance with Laws.** Each Party shall perform all of its obligations under this Agreement in compliance at all times with all applicable foreign, federal, state, and local statutes, orders, and regulations, including those relating to privacy and data protection.

**(b) Data Housing, Sub-processors, and the ECD Platform.** Client authorizes ECD and ECD’s Affiliates to ingest, store, index, and process Client Materials and Client data within the ECD Platform for the purpose of delivering, analyzing, reporting on, and improving the Services provided to Client. Client Materials and Client data are logically segregated within the ECD Platform on a per-client basis, are not disclosed to or made accessible by any other ECD client, and remain subject to the confidentiality obligations set forth in Section 12 and the post-termination return and deletion obligations set forth in Section 5(g), each of which applies to each such Affiliate to the same extent it applies to ECD. Upon Client’s written request, ECD will identify the Affiliates then processing Client data. ECD’s rights with respect to Aggregated Data, including for cross-client benchmarking, analytics, and product development, are set forth in Section 6(d). Upon Client’s written request, ECD will identify any sub-processor or artificial intelligence tool with access to Client Materials or Client data and the general location where such data is hosted or processed.

**(c) Artificial Intelligence Tools.**

(i) Use. ECD uses artificial intelligence tools, including Anthropic’s Claude and Claude Code (collectively, “AI Tools”), as part of its standard methodology to assist with research, analysis, data review, reporting, code, copy drafting, and the preparation of Service Deliverables. Client acknowledges and consents to such use.

(ii) Commercial Terms; No Model Training. ECD accesses AI Tools exclusively through paid commercial or enterprise accounts governed by the vendor’s commercial terms of service, and not through consumer or free-tier products. Under those commercial terms, Client Materials, Client data, Confidential Information, prompts, and outputs are not used to train, fine-tune, or improve the vendor’s models, and are not made available to other customers of the vendor. ECD shall not knowingly enable, and shall use commercially reasonable efforts to disable, any setting that would permit Client data to be used for model training.

(iii) Security and Confidentiality. AI Tools are treated as sub-processors under Section 9(b) and are subject to the same safeguards. Access is limited to ECD personnel with a need to know, under ECD’s account controls and authentication requirements. Data transmitted to AI Tools is encrypted in transit and at rest by the vendor, and is retained by the vendor only for the limited period permitted under the applicable commercial terms. ECD shall not input Client data into any AI Tool beyond what is reasonably necessary to perform the Services, and shall not input payment card data, government identifiers, protected health information, or other special categories of sensitive personal data into any AI Tool absent Client’s prior written authorization.

(iv) Human Review; ECD Remains Responsible. All Service Deliverables are reviewed by qualified ECD personnel before delivery to Client. ECD’s use of AI Tools does not reduce, limit, delegate, or otherwise modify any of ECD’s obligations, representations, or warranties under this Agreement, including those in Sections 7, 9, and 12. ECD is fully responsible for each Service Deliverable as if it had been produced entirely by ECD personnel without the assistance of AI Tools. Client acknowledges that AI Tools are probabilistic and may produce output requiring correction, and that this is the reason for ECD’s human review; nothing in this Section shall be read to expand the warranties given in Section 7 or to create a warranty that any Service Deliverable is error-free.

(v) Transparency and Opt-Out. Upon Client’s written request, ECD will identify the AI Tools then in use that have access to Client Materials or Client data, the vendor, and the general location where such data is processed or hosted, and will provide a copy of or link to the applicable vendor commercial terms. Client may direct ECD in writing to cease using AI Tools in connection with Client’s account, in whole or with respect to specified data or categories of work. ECD will comply within a commercially reasonable period, and the Parties acknowledge that such a direction may affect Service timelines, scope, and fees, which the Parties will address by written change order under Section 3(a).

(vi) Intellectual Property. The ownership and assignment provisions of Section 6 apply to all Service Deliverables regardless of whether AI Tools were used in their preparation, and ECD’s assignment obligations under Section 6(b) are not diminished by such use.

**(d) Messaging, Telemarketing, and Consumer Protection Compliance.**

(i) Client Is the Sender of Record. Client is and at all times remains the sender, initiator, and message originator of all email, SMS, MMS, RCS, push, direct mail, and voice communications transmitted in connection with the Services, regardless of which Party drafts, schedules, builds, or deploys such communications. ECD acts solely as Client’s service provider and at Client’s direction. All messaging platforms, sending accounts, toll-free numbers, short codes, 10DLC registrations, and sender identities are owned and controlled by Client.

(ii) Client Responsibility for Consent and Compliance. Client is solely responsible for compliance with all laws, rules, regulations, industry standards, and platform and carrier requirements applicable to such communications, including without limitation the Telephone Consumer Protection Act, 47 U.S.C. § 227 and its implementing regulations (the “TCPA”), the Telemarketing Sales Rule, the CAN-SPAM Act, applicable state telemarketing, telephone solicitation, and consumer protection statutes (including but not limited to the Florida Telephone Solicitation Act, the Oklahoma Telephone Solicitation Act, and comparable state laws), CTIA Messaging Principles and Best Practices, wireless carrier requirements, and the acceptable use policies and terms of service of Client’s messaging platforms. Without limiting the foregoing, Client is solely responsible for: (A) obtaining, documenting, and maintaining prior express written consent, and any other legally required consent, from every recipient before any message is sent; (B) the accuracy, provenance, and lawfulness of every telephone number, email address, and contact record supplied to or used in connection with the Services; (C) honoring opt-out, revocation, “STOP,” and “HELP” requests, and maintaining accurate and current suppression, do-not-call, and unsubscribe lists; (D) observing applicable quiet hours, frequency limits, sender identification, and disclosure requirements; (E) all required registrations and approvals with carriers, aggregators, and messaging platforms; and (F) the final approval of all message content, offers, disclosures, cadence, timing, and audience targeting.

(iii) Client Approval Is Authorization. Client’s approval of any message, campaign, flow, automation, audience, segment, or send schedule (email approval being sufficient) constitutes Client’s representation that the communication and its intended recipients comply with all requirements of Section 9(d)(ii), and constitutes Client’s authorization for ECD to build, schedule, and deploy the same. Where ECD deploys a message pursuant to Client’s approval, or pursuant to a standing approval, template, or automation previously approved by Client, ECD shall be deemed to have acted at Client’s express direction.

(iv) No Legal Advice; No Compliance Warranty. ECD is not a law firm and provides no legal advice. Any observation, recommendation, template, disclosure language, consent language, or best practice suggested by ECD is provided for convenience only, is not legal advice, may not reflect current law or the requirements of Client’s particular jurisdiction or industry, and shall not be relied upon as a determination of legal compliance. ECD does not represent or warrant that any communication, list, consent record, opt-in mechanism, or campaign complies with the TCPA or any other law, rule, standard, or platform requirement. Client is advised, and acknowledges that ECD has advised Client, to have its own legal counsel review its consent language, opt-in mechanisms, disclosures, and messaging program.

(v) Recommended Safeguards. ECD recommends that Client engage a qualified third-party messaging compliance provider to perform ongoing consent capture auditing, list hygiene, known-litigator and serial-plaintiff scrubbing, and regulatory monitoring. ECD will provide the names of providers upon request as a convenience only. Client contracts with any such provider directly, and ECD makes no representation or warranty as to, and shall have no liability arising from, the performance, findings, or omissions of any such provider. Client’s decision to engage or not engage such a provider is Client’s alone.

(vi) Indemnification. Client shall indemnify, defend, and hold harmless ECD, its members, officers, employees, and contractors from and against any and all Claims, losses, liabilities, damages, penalties, fines, statutory damages, settlements, expenses, and costs (including reasonable attorneys’ fees and court costs) arising out of or relating to: (A) any alleged violation of the TCPA, the Telemarketing Sales Rule, the CAN-SPAM Act, any state telemarketing, telephone solicitation, or consumer protection law, CTIA guidelines, or carrier or platform requirements, in connection with any communication sent in connection with the Services; (B) the absence, insufficiency, or invalidity of consent for any recipient; (C) the content, offers, disclosures, cadence, timing, or audience of any communication approved by Client; or (D) any contact data, list, or consent record supplied by Client or maintained in Client’s platforms. This indemnity does not apply to the extent a Claim is caused by ECD’s gross negligence or willful misconduct, including ECD’s deployment of a communication that Client did not approve and that ECD sent in disregard of Client’s written instructions. This indemnity survives termination or expiration of this Agreement.

(vii) Allocation of Liability. ECD’s aggregate liability for any Claim described in Section 9(d)(vi) shall in all events be subject to the limitations set forth in Section 11, and neither Party shall be liable to the other for statutory damages, treble damages, or civil penalties assessed under the TCPA or any comparable statute except to the extent such amounts are the subject of a Party’s indemnification obligations under this Agreement.

**(e) Website Accessibility.**

(i) ECD’s Standard of Performance. Where a SOW includes website design, development, or ongoing site support, ECD will apply commercially reasonable, then-current accessibility best practices, targeting substantial conformance with the Web Content Accessibility Guidelines (“WCAG”) version and conformance level identified in the applicable SOW, and, if no version and level is identified, WCAG 2.1 Level AA, in each case as to the pages, templates, and components expressly within the scope of that SOW. Accessibility work is limited to what the SOW describes. Remediation of pages, templates, applications, or content outside that scope is a separate engagement requiring its own SOW.

(ii) No Warranty of Legal Compliance. Client acknowledges that: (A) accessibility standards, technical guidance, judicial interpretation, regulatory rulemaking, and enforcement practice under the Americans with Disabilities Act (the “ADA”), Section 508 of the Rehabilitation Act, state accessibility and public accommodation statutes, the European Accessibility Act, and comparable authorities continue to change; (B) there is no government certification, safe harbor, or definitive technical standard that establishes ADA compliance for a commercial website; (C) a website is a living system whose accessibility posture changes every time content, products, apps, themes, integrations, or browsers change; and (D) automated accessibility testing tools produce differing and incomplete results and do not establish compliance. Accordingly, and notwithstanding Section 7(b)(ii), ECD DOES NOT REPRESENT, WARRANT, OR GUARANTEE THAT ANY WEBSITE, PAGE, TEMPLATE, SERVICE DELIVERABLE, OR CLIENT PROPERTY IS, WILL BE, OR WILL REMAIN COMPLIANT WITH OR CONFORMANT TO THE ADA, SECTION 508, WCAG, THE EUROPEAN ACCESSIBILITY ACT, OR ANY OTHER ACCESSIBILITY LAW, REGULATION, STANDARD, OR GUIDELINE, AND ECD DISCLAIMS ALL SUCH WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. ECD is not a law firm and provides no legal advice regarding accessibility obligations.

(iii) Matters Outside ECD’s Control. ECD shall have no responsibility or liability for accessibility barriers arising from: (A) third-party themes, applications, plug-ins, widgets, scripts, embeds, fonts, payment or checkout flows, reviews, chat, or other software not authored by ECD, including anything published by a platform such as Shopify or its app ecosystem; (B) content, copy, images, video, audio, PDFs, or documents supplied, uploaded, or edited by Client or any third party, including user-generated content; (C) modifications to the Service Deliverables made by Client or anyone other than ECD, including any Store-Side Execution; (D) changes in accessibility standards, guidance, or law occurring after the applicable Service Deliverable is delivered; or (E) any period following the completion or termination of the applicable SOW during which ECD is not engaged to maintain the property.

(iv) Recommended Ongoing Monitoring. Because accessibility is a continuing obligation rather than a one-time deliverable, ECD recommends that any Client that requires or desires ongoing accessibility conformance engage a dedicated accessibility monitoring and remediation service, and, where the Client’s risk profile warrants it, obtain periodic manual audits performed by qualified accessibility specialists, including testing with assistive technology and users with disabilities. ECD will, upon request, provide the names of providers it is aware of as a convenience only. Client contracts with any such provider directly. ECD makes no representation or warranty as to, and shall have no liability arising from, the selection, performance, findings, methodology, or omissions of any such provider, and Client acknowledges that some accessibility products, including automated overlay and widget solutions, are themselves the subject of litigation and professional criticism and may not reduce, and in some circumstances may increase, Client’s exposure. Client is solely responsible for evaluating and selecting its accessibility strategy and providers, and for obtaining its own legal counsel’s advice regarding its accessibility obligations.

(v) Client Responsibility and Indemnification. As between the Parties, Client is solely responsible for the accessibility and legal compliance of its websites, applications, and digital properties. Client shall indemnify, defend, and hold harmless ECD, its members, officers, employees, and contractors from and against any and all Claims, losses, liabilities, damages, penalties, settlements, expenses, and costs (including reasonable attorneys’ fees and court costs) brought by any third party, or by any governmental or regulatory authority, alleging that any website, application, or digital property of Client is inaccessible to or discriminates against persons with disabilities, or fails to comply with the ADA, Section 508, WCAG, or any comparable accessibility law, regulation, or standard, except to the extent such Claim arises directly from ECD’s failure to perform the accessibility work expressly required by an applicable SOW in accordance with Section 9(e)(i). This indemnity survives termination or expiration of this Agreement.

(vi) Remedy for Nonconformance. If Client notifies ECD in writing that a page or component expressly within the scope of a SOW materially fails to meet the accessibility target stated in Section 9(e)(i), ECD will, at Client’s request, use commercially reasonable efforts to remediate the identified nonconformance pursuant to a new or amended SOW at ECD’s then-current rates. Accessibility remediation is not included in any SOW unless that SOW expressly provides for it. Such remediation is ECD’s sole obligation, and Client’s sole and exclusive remedy, with respect to any accessibility-related claim against ECD.

**(f) Advertising Claims, Substantiation, and Client Materials.**

(i) Client Responsibility for Accuracy and Substantiation. Client is solely responsible for the truth, accuracy, completeness, and substantiation of all claims, statements, representations, product descriptions, ingredient and sourcing information, performance and results claims, pricing, discounts, availability, specifications, guarantees, testimonials, endorsements, reviews, statistics, and before-and-after or comparative imagery that Client supplies to ECD, directs ECD to use, or approves for publication (collectively, “Client Claims”). Client represents and warrants that, at the time any Client Claim is made, Client possesses and will retain competent and reliable evidence substantiating that claim, including competent and reliable scientific evidence where the nature of the claim requires it, and that each Client Claim and all Client Materials are truthful, not misleading, and lawful.

(ii) ECD May Rely; No Duty to Verify. ECD may rely on Client Materials, Client Claims, and Client approvals as accurate, substantiated, and lawful without independent investigation. ECD has no duty to verify, audit, fact-check, substantiate, or obtain evidence supporting any Client Claim, and no duty to review Client’s products, formulations, labeling, testing, certifications, or business practices. ECD is not responsible for the legality, safety, quality, fitness, or availability of Client’s products or services.

(iii) Regulated Claim Categories. Without limiting Section 9(f)(i), Client is solely responsible for compliance with all laws, rules, regulations, and industry guidance applicable to its advertising and marketing, including without limitation: Section 5 of the Federal Trade Commission Act and FTC guidance, including the Guides Concerning the Use of Endorsements and Testimonials in Advertising (16 C.F.R. Part 255), the Guides for the Use of Environmental Marketing Claims (16 C.F.R. Part 260), the Made in USA Labeling Rule, and rules governing unfair or deceptive fees and negative option and automatic renewal offers; the Federal Food, Drug, and Cosmetic Act and applicable FDA and FTC requirements for food, dietary supplement, cosmetic, over-the-counter drug, device, and health-related claims, including structure and function claims and any required disclaimers; the Restore Online Shoppers’ Confidence Act and state automatic renewal, free trial, subscription, and reference pricing statutes; the Lanham Act and state false advertising, unfair competition, and consumer protection statutes; and all requirements applicable to claims regarding sustainability, sourcing, certification, clinical results, or safety. Client is likewise solely responsible for holding all rights necessary to use the Client Materials, including rights in third-party photography, video, music, fonts, trademarks, influencer content, and user-generated content.

(iv) Approvals. Client’s approval of any copy, creative, design, landing page, advertisement, email, SMS, or other material (email approval being sufficient) constitutes Client’s representation that the material and every Client Claim in it is accurate, substantiated, and lawful, and constitutes Client’s authorization for ECD to publish or deploy the same. ECD’s drafting, editing, recommending, or suggesting of copy or creative is not, and shall not be relied upon as, a determination that any Client Claim is accurate, substantiated, or lawful. ECD is not a law firm and provides no legal or regulatory advice regarding advertising claims.

(v) Right to Decline. ECD may, at any time and without liability, decline to create, publish, or deploy, or may pause or remove, any material that ECD believes in good faith to be inaccurate, unsubstantiated, misleading, unlawful, or in violation of the terms, policies, or acceptable use requirements of any third-party platform. Any such action shall not constitute a breach of this Agreement or of any SOW, and does not limit ECD’s rights under Section 5(f).

(vi) Indemnification. Client shall indemnify, defend, and hold harmless ECD, its members, officers, employees, and contractors from and against any and all Claims, losses, liabilities, damages, penalties, fines, settlements, expenses, and costs (including reasonable attorneys’ fees and court costs) brought by any third party, or by any governmental, regulatory, or self-regulatory authority (including the Federal Trade Commission, the Food and Drug Administration, any state attorney general, and the National Advertising Division), arising out of or relating to: (A) the falsity, deceptiveness, or lack of substantiation of any Client Claim; (B) any Client Materials, or the use of Client Materials as directed or approved by Client; (C) Client’s products or services, including product liability, recall, labeling, and safety matters; or (D) Client’s pricing, discount, subscription, free trial, or automatic renewal practices. This indemnity is in addition to, and without duplication of, Client’s indemnification obligation with respect to Intellectual Property Rights under Section 10(b)(i). This indemnity does not apply to the extent a Claim is caused by ECD’s gross negligence or willful misconduct. This indemnity survives termination or expiration of this Agreement.

(g) Survival. This Section 9 shall survive the expiration or termination of this Agreement.

**10. Indemnification**
(a) Indemnification by ECD. Subject to Sections 10(c), (d), and (e), ECD will, at its expense and under its control (including selection of counsel), indemnify, defend, and hold harmless Client against any and all losses, liabilities, damages, expenses, and costs (including attorneys’ fees and court costs) arising out of any claim, suit, or proceeding brought by a third party (each, a “Claim”) against Client alleging: (i) any negligence, willful misconduct, or fraud by ECD in connection with performing the Services; and (ii) infringement or misappropriation of any third-party Intellectual Property Rights by ECD in connection with the Services or Service Deliverables.

(b) Indemnification by Client. Subject to Sections 10(c), (d), and (e), Client will, at its expense, indemnify, defend, and hold harmless ECD against any and all Claims against ECD alleging: (i) infringement or misappropriation of any third-party Intellectual Property Rights by Client in connection with the Client Materials, either alone or as incorporated into a Service Deliverable; (ii) Client’s modification of the Service Deliverables without ECD’s written consent; (iii) any matter for which Client has agreed to indemnify ECD under Section 9(d)(vi); (iv) any matter for which Client has agreed to indemnify ECD under Section 9(e)(v); or (v) any matter for which Client has agreed to indemnify ECD under Section 9(f)(vi).

(c) Exclusions. ECD will have no indemnification obligation under Section 10(a) with respect to any Claim arising out of or based upon: (i) Client’s modification of the Service Deliverables; (ii) Client’s use of the Service Deliverables with materials not originally contained therein by ECD; (iii) Client Materials used with or incorporated in the Service Deliverable in breach of this Agreement or in violation of any third-party Intellectual Property Right; (iv) any communication sent in connection with the Services, to the extent the Claim arises under the TCPA or any other telemarketing, messaging, or consumer protection law or standard, as further described in Section 9(d); (v) the accessibility of any website, application, or digital property, as further described in Section 9(e); or (vi) any Client Claim or Client Materials, as further described in Section 9(f).

(d) Procedure. If a Party (the “Indemnitee”) receives notice of a Claim with respect to which the other Party (the “Indemnitor”) has an obligation of indemnity hereunder, the Indemnitee must, within twenty (20) days of receipt of such notice, give the Indemnitor written notice of such Claim setting forth in reasonable detail the facts and circumstances surrounding the claim. The Indemnitee will not make any payment or incur any costs with respect to such Claim except as requested by the Indemnitor. The Indemnitor shall assume full control of the defense or settlement of such Claim, including selection of counsel, and shall pay all authorized and documented costs and expenses of such defense. Indemnitee may retain separate co-counsel at its sole cost and expense. If the Indemnitor fails to assume the defense within ten (10) days after written notice thereof, Indemnitee may contest, defend, settle, or compromise any such Claim, and Indemnitor shall pay Indemnitee’s reasonable attorneys’ fees and expenses.

(e) Exclusive Remedies. The indemnity and other remedies set forth in this Section 10 shall be the exclusive remedies of the Parties with respect to any claim for which a Party has an indemnification obligation pursuant to this Section 10. For the avoidance of doubt, the indemnities set forth in Sections 9(d)(vi), 9(e)(v), and 9(f)(vi) are indemnification obligations under this Agreement, are in addition to and not limited by this Section 10, and are subject to the procedure set forth in Section 10(d).

**11. Limitation of Liability**
TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER PARTY WILL BE LIABLE FOR ANY LOSS OF USE, INTERRUPTION OF BUSINESS, LOST PROFITS, OR ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES OF ANY KIND REGARDLESS OF THE FORM OF ACTION WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT PRODUCT LIABILITY, WARRANTY, OR OTHERWISE ARISING FROM ANY ASPECT OF THE SERVICES OR RELATIONSHIP PROVIDED FOR HEREIN, EVEN IF THAT PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. EXCEPT FOR A PARTY’S INDEMNIFICATION OBLIGATIONS IN THIS AGREEMENT (INCLUDING THOSE SET FORTH IN SECTIONS 9(D)(VI), 9(E)(V), 9(F)(VI), 10(A), AND 10(B)), IN THE EVENT OF ANY CLAIM FOR BREACH OF THIS AGREEMENT, EACH PARTY’S AGGREGATE LIABILITY UNDER THIS AGREEMENT WILL NOT EXCEED THE AGGREGATE PAYMENTS MADE BY CLIENT UNDER THE APPLICABLE SOW OR AGREEMENT.

**12. Confidentiality and Non-Disclosure**
(a) Definition of Confidential Information. “Confidential Information” means any non-public information disclosed by one Party (the “Disclosing Party”) to the other Party (the “Receiving Party”) in connection with this Agreement, whether disclosed orally, in writing, or by any other means, including but not limited to: business plans, financial data, pricing, customer lists, technical specifications, marketing strategies, trade secrets, proprietary processes, software, designs, and any other information that a reasonable person would consider confidential given the nature of the information and the circumstances of disclosure.

(b) Mutual Obligations. Each Party agrees to: (i) hold the other Party’s Confidential Information in strict confidence using at least the same degree of care it uses to protect its own confidential information, but in no event less than reasonable care; (ii) not disclose any Confidential Information to any third party without prior written consent of the Disclosing Party; (iii) use the Confidential Information solely to perform its obligations or exercise its rights under this Agreement; and (iv) limit access to Confidential Information to employees, contractors, advisors, affiliates, and sub-processors who have a need to know and are bound by confidentiality obligations no less restrictive than those herein.

(c) Exclusions. The obligations of confidentiality shall not apply to information that: (i) is or becomes publicly available through no fault of the Receiving Party; (ii) was already known to the Receiving Party prior to disclosure, as evidenced by written records; (iii) is independently developed by the Receiving Party without use of the Disclosing Party’s Confidential Information; (iv) is required to be disclosed by applicable law or court order, provided the Receiving Party gives prompt prior written notice and cooperates in seeking a protective order; or (v) constitutes Aggregated Data as defined in Section 6(d).

(d) Pricing Confidentiality. All pricing terms, rates, and fee structures set forth in this Agreement or any SOW are strictly confidential. Client agrees not to disclose any pricing information to any third party without ECD’s prior written consent.

(e) Duration. The confidentiality obligations set forth in this Section shall remain in effect during the term of this Agreement and for a period of three (3) years following its termination or expiration.

(f) Injunctive Relief. Each Party acknowledges that any breach of this Section may cause irreparable harm for which monetary damages would be an inadequate remedy, and that the Disclosing Party shall be entitled to seek equitable relief, including injunction and specific performance, in addition to all other remedies available at law or in equity.

**13. Notice**
Whenever notice is to be given under the terms of this Agreement, such notice shall be deemed given: (a) when received by the addressee, if delivered by hand; (b) on the date mailed when sent by certified mail, return receipt requested, and deposited at a U.S. Post Office; (c) when received by the addressee, if sent by a nationally-recognized overnight delivery service; or (d) when sent by email with confirmation of delivery receipt. Notice shall be addressed as follows, or such other address as either Party may provide by like notice:

If to ECD: ECD Digital Strategy, Attn: Zak Cassady-Dorion, 1114 Ruffner Rd, Niskayuna, NY 12309. If to Client: the address on file for Client as provided at signing.

**14. Governing Law and Jurisdiction**
The substantive and procedural laws of the State of New York, without regard to conflicts of law principles, will govern all questions concerning the construction, validity, and interpretation of this Agreement and the performance of the obligations imposed by this Agreement. The Parties irrevocably submit to the venue, personal, and subject matter jurisdiction of the courts sitting in Schenectady County, New York, or the appropriate United States District Court for the Northern District of New York, as the case may be, over any suit, action, or proceeding arising out of or relating to this Agreement. The Parties irrevocably waive, to the fullest extent permitted by law, any objection they may now or hereafter have to the laying of venue, “forum non conveniens,” subject matter jurisdiction, or personal jurisdiction of any such court.

**15. Force Majeure**
Except for payments due to ECD under this Agreement, neither Party shall be liable or deemed in breach for any delay or failure in performance to the extent caused by circumstances beyond its reasonable control, including, but not limited to: acts of God, flood, fire, earthquake, explosion, or severe weather; war, invasion, hostilities, terrorist threats or acts, sabotage, or piracy; government order, law, or action; epidemic, pandemic, or other public health crisis (including quarantine or employee restrictions); strikes, slowdowns, or other labor disturbances; interruptions, outages, failures, deprecations, rate-limiting, or policy changes affecting third-party platforms, services, or infrastructure outside the affected Party’s control, including those of platforms such as Klaviyo, Shopify, Meta, and Google; internet, hosting, telecommunications, cloud, or utility disruptions; and cybersecurity incidents, data breaches, denial-of-service attacks, or malware not caused by the affected Party’s failure to maintain reasonable safeguards. The affected Party will notify the other Party as soon as reasonably practicable and use commercially reasonable efforts to mitigate and resume performance. If a force majeure event continues for more than thirty (30) consecutive days, either Party may terminate the affected SOW upon written notice, in which case Client shall pay for all Services performed through the date of termination.

**16. Entire Agreement; No Reliance**
This Agreement, together with all executed SOWs, exhibits, and the Client Operating Rules, sets forth the entire and complete agreement and understanding of the Parties concerning the subject matter hereof and supersedes all prior agreements, arrangements, and understandings between them. The Parties warrant and represent that no representations, promises, inducements, or statements of intention, oral, written, or otherwise, have been made by or on behalf of any Party concerning the subject matter hereof which are not expressly set forth in this Agreement. The Parties agree they shall not be bound and may not rely upon any representation, promise, offer, term, condition, inducement, or statement of intention of any type or kind whatsoever, whether before or after the Effective Date, which is not expressly set forth in this Agreement or contained in a written amendment executed and delivered by the Parties in accordance with Section 17.

**17. Amendment**
Except as expressly provided in Sections 3(a), 4(a), 9(d)(iii), and 9(f)(iv), this Agreement may not be altered, changed, modified, amended, or waived except in a writing executed by both Parties. No changes, deletions, additions, or interlineations made to this Agreement shall be binding unless initialed by each Party. Except as expressly provided in Sections 3(a), 4(a), 9(d)(iii), and 9(f)(iv), emails shall not change, modify, alter, or affect the terms and conditions of this Agreement. No course of dealing between the Parties will be deemed effective to modify or amend any part of this Agreement or any rights or obligations of any Party hereunder.

**18. Waiver**
The failure of any Party to enforce at any time any of the provisions of this Agreement shall in no way be construed to be a waiver of any such provision, nor in any way affect the validity of this Agreement or any part hereof, or the right of any Party to enforce each and every such provision thereafter.

**19. Validity of Agreement**
The Parties acknowledge that they each have the legal capacity and authority to enter into this Agreement. This Agreement is a legally valid and binding obligation of the Parties, fully enforceable against them in accordance with its terms.

**20. Binding Effect**
All of the terms, covenants, representations, warranties, and conditions of this Agreement shall be binding upon and inure to the benefit of and be enforceable by the Parties and their respective successors and permitted assigns.

**21. Severability**
If any provision of this Agreement is held by a court of competent jurisdiction to be invalid, illegal, or unenforceable in any respect, such invalidity, illegality, or unenforceability shall not affect the remainder of this Agreement. The Agreement shall be construed as if such invalid, illegal, or unenforceable provision had not been contained herein, but only to the extent it is invalid, illegal, or unenforceable.

**22. Independent Contractors**
Each Party is an independent contractor of the other Party. This Agreement shall not be construed to create any association, partnership, joint venture, employee, or agency relationship between the Parties for any purpose. Neither Party has any authority (and shall not hold itself out as having authority) to bind the other Party, and neither Party shall make any agreements or representations on the other Party’s behalf without its prior written consent.

**23. No Assignment**
Neither Party may assign this Agreement or any rights, duties, or obligations hereunder without prior written consent of the other Party; provided, however, that ECD may, without such consent, permit its Affiliates to perform Services and to access Client Materials and Client data as contemplated by Section 9(b), and may assign this Agreement in connection with a merger, reorganization, or sale of all or substantially all of its assets or equity. This Agreement is solely for the benefit of ECD and Client. No other Person shall have the right to rely upon any of the terms, conditions, or rights hereunder.

**24. Waiver of Jury Trial**
AS A MATERIAL TERM OF THIS AGREEMENT, THE PARTIES, JOINTLY AND SEVERALLY, KNOWINGLY, WILLINGLY, AND VOLUNTARILY, AND BY THEIR EXPRESS DESIRE AND INTENT, DO EXPRESSLY HEREBY WAIVE A TRIAL BY JURY ON ALL ISSUES, CLAIMS, COUNTERCLAIMS, AND CROSS-CLAIMS OF ANY KIND OR NATURE ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT.

**25. Incorporation of Exhibits and Schedules**
Any exhibits and schedules identified in this Agreement or in any SOW are incorporated herein by reference and made a part hereof as if set out in full in this Agreement.

**26. Construction**
Paragraph headings are inserted for reference only and shall not affect the construction or interpretation of this Agreement. In the event an ambiguity or question of intent or interpretation arises, this Agreement shall be construed as if drafted jointly by the Parties, and no presumption or burden of proof shall arise favoring or disfavoring any Party by virtue of the authorship of any of the provisions hereof. For purposes of this Agreement: (a) the singular shall include the plural and vice-versa; (b) a reference to an Exhibit or Schedule without a further reference to the document to which it is attached is a reference to an Exhibit or Schedule to this Agreement; and (c) the word “including” means “including, but not limited to.”

**27. Counterparts**
This Agreement may be executed simultaneously in one or more counterparts, including by fax and electronic signatures, each of which shall be deemed an original, but all of which together shall constitute one and the same instrument. The Parties agree that this Agreement may be executed by electronic means pursuant to New York Electronic Signatures and Records Act (N.Y. State Tech. Law § 301 et seq.) and the U.S. federal ESIGN Act of 2000. Electronic signatures (including those made via DocuSign, PandaDoc, or similar platforms) shall be treated as original signatures and shall be valid and effective for all purposes.$msa$,
    updated_at = now()
where slug = 'msa';

-- Proposals for a client who already signed the MSA attach this short reference
-- instead of the full template (src/lib/msa-on-file.ts). Each proposal carries
-- its own dated wording as a contract override; this text is the fallback.
insert into public.contract_documents (slug, name, content, is_active, display_order)
values ('msa_on_file', 'Master Services Agreement (on file)', $msa$**Governing Agreement**

This proposal is a Statement of Work under the Master Services Agreement already signed between ECD Digital Strategy and Client, as that agreement was executed, including any changes the parties agreed to at the time (the “MSA”).

The MSA governs this Statement of Work. It is not restated here, and nothing in this proposal amends it.$msa$, true, 11)
on conflict (slug) do update set name = excluded.name, content = excluded.content, updated_at = now();
